# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Alessandro Manfredi <a.n0on3@gmail.com>, 2015
# Daniele Catanesi <translate@ccielogs.com>, 2009
# Emma Peel, 2019
# Francesca Ciceri <madamezou@zouish.org>, 2014
# Francesca Ciceri <madamezou@zouish.org>, 2014
# Francesco Tombolini <tombo@adamantio.net>, 2009
# spawned76 <fswitch20@hotmail.com>, 2012
# Giovanni Giorgio <bottilorenzobg@gmail.com>, 2018
# jan <jan.reister@unimi.it>, 2013
# jan <jan.reister@unimi.it>, 2013
# mario_santagiuliana <mario@marionline.it>, 2009
# Michele Orrù <maker.py@gmail.com>, 2012
# Paolo Stivanin <paolostivanin@gmail.com>, 2014
# Pietro Messineo <pietromessineo@hotmail.it>, 2015
# Random_R, 2013-2015,2017-2019
# Rossano Praderi <rossano.praderi@yahoo.com>, 2013
# s r <stefano.rufini@gmail.com>, 2017
# spawned76 <fswitch20@hotmail.com>, 2012
# VaiTon86 <eyadlorenzo@gmail.com>, 2015
# Vincenzo Cerminara <rebek994@gmail.com>, 2013
msgid ""
msgstr ""
"Project-Id-Version: Tor Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-04-13 08:42+0200\n"
"PO-Revision-Date: 2019-04-14 07:49+0000\n"
"Last-Translator: Emma Peel\n"
"Language-Team: Italian (http://www.transifex.com/otf/torproject/language/it/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: it\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../tails_installer/creator.py:100
msgid "You must run this application as root"
msgstr "Per eseguire questa applicazione sono necessari i privilegi di root"

#: ../tails_installer/creator.py:146
msgid "Extracting live image to the target device..."
msgstr "Estrazione dell'immagine live nel dispositivo di destinazione..."

#: ../tails_installer/creator.py:153
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr "Scrittura eseguita a %(speed)d MB/sec"

#: ../tails_installer/creator.py:296
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr "Si è verificato un problema durante l'esecuzione del comando: `%(command)s`.\nPer visualizzare ulteriori dettagli aprire il file '%(filename)s'."

#: ../tails_installer/creator.py:315
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr "Verifica SHA1 dell'immagine LiveCD in corso..."

#: ../tails_installer/creator.py:319
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr "Verifica SHA256 dell'immagine LiveCD in corso..."

#: ../tails_installer/creator.py:335
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr "Errore: lo SHA1 del Live CD non è valido. È possibile eseguire il programma con l'opzione --noverify per non eseguire la verifica."

#: ../tails_installer/creator.py:341
msgid "Unknown ISO, skipping checksum verification"
msgstr "Immagine ISO sconosciuta: la verifica del checksum non verrà eseguita"

#: ../tails_installer/creator.py:353
#, python-format
msgid ""
"Not enough free space on device.\n"
"%dMB ISO + %dMB overlay > %dMB free space"
msgstr "Spazio libero sul dispositivo insufficiente.\n%dMB ISO + %dMB overlay > %dMB spazio libero"

#: ../tails_installer/creator.py:360
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "Creazione overlay persistente %s MB"

#: ../tails_installer/creator.py:421
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr "Impossibile effettuare la copia da %(infile)s a %(outfile)s: %(message)s"

#: ../tails_installer/creator.py:435
msgid "Removing existing Live OS"
msgstr "Il Live OS esistente è in fase di cancellazione"

#: ../tails_installer/creator.py:444 ../tails_installer/creator.py:457
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr "Impossibile completare il comando chmod %(file)s: %(message)s"

#: ../tails_installer/creator.py:450
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr "Impossibile rimuovere il file della precedente LiveOS: %(message)s"

#: ../tails_installer/creator.py:464
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr "Impossibile rimuovere la directory della precendente LiveOS: %(message)s"

#: ../tails_installer/creator.py:512
#, python-format
msgid "Cannot find device %s"
msgstr "Impossibile trovare il dispositivo %s"

#: ../tails_installer/creator.py:713
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr "Impossibile scrivere su %(device)s, operazione ignorata."

#: ../tails_installer/creator.py:743
#, python-format
msgid ""
"Some partitions of the target device %(device)s are mounted. They will be "
"unmounted before starting the installation process."
msgstr "Alcune partizioni del dispositivo di destinazione %(device)s sono montate. Verranno smontate prima di iniziare il processo di installazione."

#: ../tails_installer/creator.py:786 ../tails_installer/creator.py:1010
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr "Filesystem sconosciuto. Potrebbe essere necessario formattare il disco di nuovo."

#: ../tails_installer/creator.py:789 ../tails_installer/creator.py:1013
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "Filesystem non supportato: %s"

#: ../tails_installer/creator.py:807
#, python-format
msgid "Unknown GLib exception while trying to mount device: %(message)s"
msgstr "Eccezione GLib sconosciuta tentando di montare il dispositivo: %(message)s"

#: ../tails_installer/creator.py:812
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr "Impossibile eseguire il mount del dispositivo: %(message)s"

#: ../tails_installer/creator.py:817
msgid "No mount points found"
msgstr "Nessun punto di mount definito"

#: ../tails_installer/creator.py:828
#, python-format
msgid "Entering unmount_device for '%(device)s'"
msgstr "Inserire unmount_device per '%(device)s'"

#: ../tails_installer/creator.py:838
#, python-format
msgid "Unmounting mounted filesystems on '%(device)s'"
msgstr "Smontaggio dei filesystem montati su '%(device)s'"

#: ../tails_installer/creator.py:842
#, python-format
msgid "Unmounting '%(udi)s' on '%(device)s'"
msgstr "Smontaggio di '%(udi)s' su '%(device)s'"

#: ../tails_installer/creator.py:853
#, python-format
msgid "Mount %s exists after unmounting"
msgstr "Mount %s esiste dopo l'operazione di unmount"

#: ../tails_installer/creator.py:866
#, python-format
msgid "Partitioning device %(device)s"
msgstr "Partizionamento dispositivo %(device)s"

#: ../tails_installer/creator.py:995
#, python-format
msgid "Unsupported device '%(device)s', please report a bug."
msgstr "Dispositivo '%(device)s' non supportato, si prega di segnalare l'errore."

#: ../tails_installer/creator.py:998
msgid "Trying to continue anyway."
msgstr "Tentativo di continuare comunque."

#: ../tails_installer/creator.py:1007 ../tails_installer/creator.py:1405
msgid "Verifying filesystem..."
msgstr "Verifica del filesystem in corso..."

#: ../tails_installer/creator.py:1031
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr "Impossibile cambiare l'etichetta di volume: %(message)s"

#: ../tails_installer/creator.py:1037 ../tails_installer/creator.py:1440
msgid "Installing bootloader..."
msgstr "Installazione bootloader..."

#: ../tails_installer/creator.py:1064
#, python-format
msgid "Could not find the '%s' COM32 module"
msgstr "Impossibile trovare il modulo '%s' COM32"

#: ../tails_installer/creator.py:1072 ../tails_installer/creator.py:1458
#, python-format
msgid "Removing %(file)s"
msgstr "Cancellazione %(file)s in corso"

#: ../tails_installer/creator.py:1186
#, python-format
msgid "%s already bootable"
msgstr "%s è già avviabile"

#: ../tails_installer/creator.py:1206
msgid "Unable to find partition"
msgstr "Impossibile trovare la partizione"

#: ../tails_installer/creator.py:1229
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr "Formattazione %(device)s con filesystem FAT32"

#: ../tails_installer/creator.py:1289
msgid "Could not find syslinux' gptmbr.bin"
msgstr "Impossibile trovare syslinux' gptmbr.bin"

#: ../tails_installer/creator.py:1302
#, python-format
msgid "Reading extracted MBR from %s"
msgstr "Lettura MBR estratto da %s"

#: ../tails_installer/creator.py:1306
#, python-format
msgid "Could not read the extracted MBR from %(path)s"
msgstr "Impossibile leggere MBR estratto da %(path)s"

#: ../tails_installer/creator.py:1319 ../tails_installer/creator.py:1320
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr "Reset del Master Boot Record di %s in corso"

#: ../tails_installer/creator.py:1325
msgid "Drive is a loopback, skipping MBR reset"
msgstr "Il drive è una unità di loopback, operazione di reset del MBR ignorata"

#: ../tails_installer/creator.py:1329 ../tails_installer/creator.py:1589
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr "Calcolo SHA1 di %s"

#: ../tails_installer/creator.py:1354
msgid "Synchronizing data on disk..."
msgstr "Sincronizzazione dati sul disco..."

#: ../tails_installer/creator.py:1397
msgid "Error probing device"
msgstr "Errore durante la rilevazione della periferica"

#: ../tails_installer/creator.py:1399
msgid "Unable to find any supported device"
msgstr "Nessun dispositivo supportato trovato"

#: ../tails_installer/creator.py:1409
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr "Assicurarsi che il pendrive USB sia collegato e formattato con filesystem FAT"

#: ../tails_installer/creator.py:1412
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "Filesystem non supportato: %s\nEseguire un backup e formattare il pendrive USB con il filesystem FAT."

#: ../tails_installer/creator.py:1481
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr "Impossibile trovare Win32_LogicalDisk; win32com non ha restituito nessun risultato"

#: ../tails_installer/creator.py:1536
msgid "Cannot find"
msgstr "Impossibile trovare"

#: ../tails_installer/creator.py:1537
msgid ""
"Make sure to extract the entire tails-installer zip file before running this"
" program."
msgstr "Assicurati di estrarre l'intero file zip con l'installer di Tails prima di avviare questo programma."

#: ../tails_installer/gui.py:69
#, python-format
msgid "Unknown release: %s"
msgstr "Release sconosciuta: %s"

#: ../tails_installer/gui.py:73
#, python-format
msgid "Downloading %s..."
msgstr "Download di %s in corso"

#: ../tails_installer/gui.py:213
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "Errore: impossibile impostare l'etichetta o ottenere l'UUID del dispositivo. Impossibile continuare."

#: ../tails_installer/gui.py:260
#, python-format
msgid "Installation complete! (%s)"
msgstr "Installazione completata! (%s)"

#: ../tails_installer/gui.py:265
msgid "Tails installation failed!"
msgstr "Installazione di Tails fallita!"

#: ../tails_installer/gui.py:369
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr "Attenzione: questo programma necessita dei permessi di amministratore. Per poterlo aprire, fai click destro sull'icona, quindi su \"Proprietà\". Sotto la scheda Compatibilità, click sulla box \"Apri questo programma come Administrator\""

#: ../tails_installer/gui.py:381
msgid "Tails Installer"
msgstr "Installer di Tails"

#: ../tails_installer/gui.py:441
msgid "Tails Installer is deprecated in Debian"
msgstr "L'installer di Tails è deprecato in Debian"

#: ../tails_installer/gui.py:443
msgid ""
"To install Tails from scratch, use GNOME Disks instead.\n"
"<a href='https://tails.boum.org/install/linux/usb-overview'>See the installation instructions</a>\n"
"\n"
"To upgrade Tails, do an automatic upgrade from Tails or a manual upgrade from Debian using a second USB stick.\n"
"<a href='https://tails.boum.org/upgrade/tails-overview'>See the manual upgrade instructions</a>"
msgstr "Per installare Tails da zero, usa il programma \"Dischi\" di GNOME.\n<a href='https://tails.boum.org/install/linux/usb-overview'>Vedi le istruzioni di installazione</a>\n\nPer aggiornare Tails, fai un aggiornamento automatico da Tails o uno manuale da Debian usando una penna USB secondaria.\n<a href='https://tails.boum.org/upgrade/tails-overview'>Vedi le istruzioni di aggiornamento manuale</a>"

#: ../tails_installer/gui.py:450 ../data/tails-installer.ui.h:2
msgid "Clone the current Tails"
msgstr "Clona l'attuale Tails"

#: ../tails_installer/gui.py:457 ../data/tails-installer.ui.h:3
msgid "Use a downloaded Tails ISO image"
msgstr "Usa un'immagine ISO di Tails scaricata"

#: ../tails_installer/gui.py:494 ../tails_installer/gui.py:815
msgid "Upgrade"
msgstr "Aggiorna"

#: ../tails_installer/gui.py:496
msgid "Manual Upgrade Instructions"
msgstr "Istruzioni aggiornamento manuale"

#: ../tails_installer/gui.py:498
msgid "https://tails.boum.org/upgrade/"
msgstr "https://tails.boum.org/upgrade/index.it.html"

#: ../tails_installer/gui.py:506 ../tails_installer/gui.py:727
#: ../tails_installer/gui.py:792 ../data/tails-installer.ui.h:7
msgid "Install"
msgstr "Installa"

#: ../tails_installer/gui.py:509 ../data/tails-installer.ui.h:1
msgid "Installation Instructions"
msgstr "Istruzioni di installazione"

#: ../tails_installer/gui.py:511
msgid "https://tails.boum.org/install/"
msgstr "https://tails.boum.org/install/"

#: ../tails_installer/gui.py:517
#, python-format
msgid "%(size)s %(vendor)s %(model)s device (%(device)s)"
msgstr "Dispositivo %(size)s %(vendor)s %(model)s (%(device)s)"

#: ../tails_installer/gui.py:529
msgid "No ISO image selected"
msgstr "Nessuna immagine ISO selezionata"

#: ../tails_installer/gui.py:530
msgid "Please select a Tails ISO image."
msgstr "Seleziona un'immagine ISO di Tails."

#: ../tails_installer/gui.py:572
msgid "No device suitable to install Tails could be found"
msgstr "Nessun dispositivo adatto all'installazione di Tails trovato"

#: ../tails_installer/gui.py:574
#, python-format
msgid "Please plug a USB flash drive or SD card of at least %0.1f GB."
msgstr "Inserisci una chiave USB o una scheda SD di almeno %0.1f GB."

#: ../tails_installer/gui.py:608
#, python-format
msgid ""
"The USB stick \"%(pretty_name)s\" is configured as non-removable by its "
"manufacturer and Tails will fail to start from it. Please try installing on "
"a different model."
msgstr "La penna USB \"%(pretty_name)s\" è configurata come non-rimovibile dal suo produttore e Tails non potrà avviarsi. Prova ad installarlo in un modello differente."

#: ../tails_installer/gui.py:618
#, python-format
msgid ""
"The device \"%(pretty_name)s\" is too small to install Tails (at least "
"%(size)s GB is required)."
msgstr "Il dispositivo \"%(pretty_name)s\" è troppo piccolo per installarci Tails (almeno %(size)s GB necessari)."

#: ../tails_installer/gui.py:631
#, python-format
msgid ""
"To upgrade device \"%(pretty_name)s\" from this Tails, you need to use a downloaded Tails ISO image:\n"
"https://tails.boum.org/install/download"
msgstr "Per aggiornare il dispositivo \"%(pretty_name)s\" da questo Tails, devi usare un'immagine ISO di Tails scaricata:\nhttps://tails.boum.org/install/download"

#: ../tails_installer/gui.py:652
msgid "An error happened while installing Tails"
msgstr "Riscontrato un errore durante l'installazione di Tails"

#: ../tails_installer/gui.py:664
msgid "Refreshing releases..."
msgstr "Ricaricamento delle release in corso..."

#: ../tails_installer/gui.py:669
msgid "Releases updated!"
msgstr "Release aggiornate!"

#: ../tails_installer/gui.py:722
msgid "Installation complete!"
msgstr "Installazione completata!"

#: ../tails_installer/gui.py:738
msgid "Cancel"
msgstr "Annulla"

#: ../tails_installer/gui.py:774
msgid "Unable to mount device"
msgstr "Impossibile montare il dispositivo"

#: ../tails_installer/gui.py:781 ../tails_installer/gui.py:814
msgid "Confirm the target USB stick"
msgstr "Conferma la penna USB di destinazione"

#: ../tails_installer/gui.py:782
#, python-format
msgid ""
"%(size)s %(vendor)s %(model)s device (%(device)s)\n"
"\n"
"All data on this USB stick will be lost."
msgstr "Dispositivo %(size)s %(vendor)s %(model)s (%(device)s)\n\nTutti i dati su questa penna USB verranno persi."

#: ../tails_installer/gui.py:801
#, python-format
msgid "%(parent_size)s %(vendor)s %(model)s device (%(device)s)"
msgstr "%(parent_size)s %(vendor)s %(model)s dispositivo (%(device)s)"

#: ../tails_installer/gui.py:809
msgid ""
"\n"
"\n"
"The persistent storage on this USB stick will be preserved."
msgstr "\n\nLa memoria persistente in questa penna USB verrà conservata."

#: ../tails_installer/gui.py:810
#, python-format
msgid "%(description)s%(persistence_message)s"
msgstr "%(description)s %(persistence_message)s"

#: ../tails_installer/gui.py:853
msgid "Download complete!"
msgstr "Download completo!"

#: ../tails_installer/gui.py:857
msgid "Download failed: "
msgstr "Download fallito:"

#: ../tails_installer/gui.py:858
msgid "You can try again to resume your download"
msgstr "È possibile tentare di ripristinare il download"

#: ../tails_installer/gui.py:866
msgid ""
"The selected file is unreadable. Please fix its permissions or select "
"another file."
msgstr "Il file selezionato è illeggibile. Si prega di modificarne i permessi o selezionare un altro file."

#: ../tails_installer/gui.py:872
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr "Impossibile aprire il file selezionato. Provare a spostare il file ISO sulla root del disco (ie: C:\\)"

#: ../tails_installer/gui.py:878
#, python-format
msgid "%(filename)s selected"
msgstr "%(filename)s selezionato/i"

#: ../tails_installer/source.py:29
msgid "Unable to find LiveOS on ISO"
msgstr "Impossibile trovare LiveOS su ISO"

#: ../tails_installer/source.py:35
#, python-format
msgid "Could not guess underlying block device: %s"
msgstr "Impossibile rilevare dispositivo a blocchi sottostante: %s"

#: ../tails_installer/source.py:50
#, python-format
msgid ""
"There was a problem executing `%s`.\n"
"%s\n"
"%s"
msgstr "Problema nell'esecuzione di `%s`.\n%s\n%s"

#: ../tails_installer/source.py:64
#, python-format
msgid "'%s' does not exist"
msgstr "'%s' non esiste"

#: ../tails_installer/source.py:66
#, python-format
msgid "'%s' is not a directory"
msgstr "'%s' non è una cartella"

#: ../tails_installer/source.py:76
#, python-format
msgid "Skipping '%(filename)s'"
msgstr "Salto '%(filename)s'"

#: ../tails_installer/utils.py:55
#, python-format
msgid ""
"There was a problem executing `%s`.%s\n"
"%s"
msgstr "Problema nell'esecuzione di `%s`.%s\n%s"

#: ../tails_installer/utils.py:135
msgid "Could not open device for writing."
msgstr "Impossibile aprire il dispositivo per la scrittura."

#: ../data/tails-installer.ui.h:4
msgid "Select a distribution to download:"
msgstr "Seleziona una distribuzione da scaricare:"

#: ../data/tails-installer.ui.h:5
msgid "Target USB stick:"
msgstr "Penna USB di destinazione:"

#: ../data/tails-installer.ui.h:6
msgid "Reinstall (delete all data)"
msgstr "Reinstalla (elimina tutti i dati)"
