# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: The Tor Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-09-14 14:52+0200\n"
"PO-Revision-Date: 2017-09-14 13:47+0000\n"
"Last-Translator: carolyn <carolyn@anhalt.org>\n"
"Language-Team: Gujarati (India) (http://www.transifex.com/otf/torproject/language/gu_IN/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: gu_IN\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../tails_installer/creator.py:101
msgid "You must run this application as root"
msgstr ""

#: ../tails_installer/creator.py:147
msgid "Extracting live image to the target device..."
msgstr ""

#: ../tails_installer/creator.py:154
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr ""

#: ../tails_installer/creator.py:184
msgid "Setting up OLPC boot file..."
msgstr ""

#: ../tails_installer/creator.py:321
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr ""

#: ../tails_installer/creator.py:340
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr ""

#: ../tails_installer/creator.py:344
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr ""

#: ../tails_installer/creator.py:360
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr ""

#: ../tails_installer/creator.py:366
msgid "Unknown ISO, skipping checksum verification"
msgstr ""

#: ../tails_installer/creator.py:377
#, python-format
msgid ""
"Not enough free space on device.\n"
"%dMB ISO + %dMB overlay > %dMB free space"
msgstr ""

#: ../tails_installer/creator.py:384
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr ""

#: ../tails_installer/creator.py:445
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:459
msgid "Removing existing Live OS"
msgstr ""

#: ../tails_installer/creator.py:468 ../tails_installer/creator.py:479
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:472
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:484
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:532
#, python-format
msgid "Cannot find device %s"
msgstr ""

#: ../tails_installer/creator.py:699
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr ""

#: ../tails_installer/creator.py:719
#, python-format
msgid ""
"Some partitions of the target device %(device)s are mounted. They will be "
"unmounted before starting the installation process."
msgstr ""

#: ../tails_installer/creator.py:762 ../tails_installer/creator.py:986
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr ""

#: ../tails_installer/creator.py:765 ../tails_installer/creator.py:989
#, python-format
msgid "Unsupported filesystem: %s"
msgstr ""

#: ../tails_installer/creator.py:782
#, python-format
msgid "Unknown GLib exception while trying to mount device: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:786
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:791
msgid "No mount points found"
msgstr ""

#: ../tails_installer/creator.py:802
#, python-format
msgid "Entering unmount_device for '%(device)s'"
msgstr ""

#: ../tails_installer/creator.py:812
#, python-format
msgid "Unmounting mounted filesystems on '%(device)s'"
msgstr ""

#: ../tails_installer/creator.py:816
#, python-format
msgid "Unmounting '%(udi)s' on '%(device)s'"
msgstr ""

#: ../tails_installer/creator.py:826
#, python-format
msgid "Mount %s exists after unmounting"
msgstr ""

#: ../tails_installer/creator.py:839
#, python-format
msgid "Partitioning device %(device)s"
msgstr ""

#: ../tails_installer/creator.py:917
#, python-format
msgid "Updating properties of system partition %(system_partition)s"
msgstr ""

#: ../tails_installer/creator.py:971
#, python-format
msgid "Unsupported device '%(device)s', please report a bug."
msgstr ""

#: ../tails_installer/creator.py:974
msgid "Trying to continue anyway."
msgstr ""

#: ../tails_installer/creator.py:983 ../tails_installer/creator.py:1376
msgid "Verifying filesystem..."
msgstr ""

#: ../tails_installer/creator.py:1007
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:1012 ../tails_installer/creator.py:1409
msgid "Installing bootloader..."
msgstr ""

#: ../tails_installer/creator.py:1038
#, python-format
msgid "Could not find the '%s' COM32 module"
msgstr ""

#: ../tails_installer/creator.py:1046 ../tails_installer/creator.py:1427
#, python-format
msgid "Removing %(file)s"
msgstr ""

#: ../tails_installer/creator.py:1158
#, python-format
msgid "%s already bootable"
msgstr ""

#: ../tails_installer/creator.py:1178
msgid "Unable to find partition"
msgstr ""

#: ../tails_installer/creator.py:1201
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr ""

#: ../tails_installer/creator.py:1261
msgid "Could not find syslinux' gptmbr.bin"
msgstr ""

#: ../tails_installer/creator.py:1274
#, python-format
msgid "Reading extracted MBR from %s"
msgstr ""

#: ../tails_installer/creator.py:1278
#, python-format
msgid "Could not read the extracted MBR from %(path)s"
msgstr ""

#: ../tails_installer/creator.py:1291 ../tails_installer/creator.py:1292
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr ""

#: ../tails_installer/creator.py:1297
msgid "Drive is a loopback, skipping MBR reset"
msgstr ""

#: ../tails_installer/creator.py:1301 ../tails_installer/creator.py:1555
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr ""

#: ../tails_installer/creator.py:1326
msgid "Synchronizing data on disk..."
msgstr ""

#: ../tails_installer/creator.py:1368
msgid "Error probing device"
msgstr ""

#: ../tails_installer/creator.py:1370
msgid "Unable to find any supported device"
msgstr ""

#: ../tails_installer/creator.py:1380
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr ""

#: ../tails_installer/creator.py:1383
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr ""

#: ../tails_installer/creator.py:1450
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr ""

#: ../tails_installer/creator.py:1503
msgid "Cannot find"
msgstr ""

#: ../tails_installer/creator.py:1504
msgid ""
"Make sure to extract the entire tails-installer zip file before running this"
" program."
msgstr ""

#: ../tails_installer/gui.py:69
#, python-format
msgid "Unknown release: %s"
msgstr ""

#: ../tails_installer/gui.py:73
#, python-format
msgid "Downloading %s..."
msgstr ""

#: ../tails_installer/gui.py:209
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr ""

#: ../tails_installer/gui.py:258
#, python-format
msgid "Installation complete! (%s)"
msgstr ""

#: ../tails_installer/gui.py:263
msgid "Tails installation failed!"
msgstr ""

#: ../tails_installer/gui.py:364
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr ""

#: ../tails_installer/gui.py:376 ../tails_installer/launcher.py:31
msgid "Tails Installer"
msgstr ""

#: ../tails_installer/gui.py:473
#, python-format
msgid "%(size)s %(vendor)s %(model)s device (%(device)s)"
msgstr ""

#: ../tails_installer/gui.py:484
msgid "No ISO image selected"
msgstr ""

#: ../tails_installer/gui.py:485
msgid "Please select a Tails ISO image."
msgstr ""

#: ../tails_installer/gui.py:524
msgid "No device suitable to install Tails could be found"
msgstr ""

#: ../tails_installer/gui.py:526
#, python-format
msgid "Please plug a USB flash drive or SD card of at least %0.1f GB."
msgstr ""

#: ../tails_installer/gui.py:560
#, python-format
msgid ""
"The USB stick \"%(pretty_name)s\" is configured as non-removable by its "
"manufacturer and Tails will fail to start on it. Please try installing on a "
"different model."
msgstr ""

#: ../tails_installer/gui.py:570
#, python-format
msgid ""
"The device \"%(pretty_name)s\" is too small to install Tails (at least "
"%(size)s GB is required)."
msgstr ""

#: ../tails_installer/gui.py:592
msgid "An error happened while installing Tails"
msgstr ""

#: ../tails_installer/gui.py:604
msgid "Refreshing releases..."
msgstr ""

#: ../tails_installer/gui.py:609
msgid "Releases updated!"
msgstr ""

#: ../tails_installer/gui.py:651
msgid "Installation complete!"
msgstr ""

#: ../tails_installer/gui.py:652
msgid "Installation was completed."
msgstr ""

#: ../tails_installer/gui.py:701
msgid "Unable to mount device"
msgstr ""

#: ../tails_installer/gui.py:708 ../tails_installer/gui.py:736
msgid "Confirm the target USB stick"
msgstr ""

#: ../tails_installer/gui.py:709
#, python-format
msgid ""
"%(size)s %(vendor)s %(model)s device (%(device)s)\n"
"\n"
"All data on this USB stick will be lost."
msgstr ""

#: ../tails_installer/gui.py:728
#, python-format
msgid ""
"%(vendor)s %(model)s device (%(device)s)\n"
"\n"
"%(persistence_message)s"
msgstr ""

#: ../tails_installer/gui.py:782
msgid "Download complete!"
msgstr ""

#: ../tails_installer/gui.py:786
msgid "Download failed: "
msgstr ""

#: ../tails_installer/gui.py:787
msgid "You can try again to resume your download"
msgstr ""

#: ../tails_installer/gui.py:795
msgid ""
"The selected file is unreadable. Please fix its permissions or select "
"another file."
msgstr ""

#: ../tails_installer/gui.py:801
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr ""

#: ../tails_installer/gui.py:807
#, python-format
msgid "%(filename)s selected"
msgstr ""

#: ../tails_installer/source.py:28
msgid "Unable to find LiveOS on ISO"
msgstr ""

#: ../tails_installer/source.py:34
#, python-format
msgid "Could not guess underlying block device: %s"
msgstr ""

#: ../tails_installer/source.py:49
#, python-format
msgid ""
"There was a problem executing `%s`.\n"
"%s\n"
"%s"
msgstr ""

#: ../tails_installer/source.py:63
#, python-format
msgid "'%s' does not exist"
msgstr ""

#: ../tails_installer/source.py:65
#, python-format
msgid "'%s' is not a directory"
msgstr ""

#: ../tails_installer/source.py:75
#, python-format
msgid "Skipping '%(filename)s'"
msgstr ""

#: ../tails_installer/utils.py:44
#, python-format
msgid ""
"There was a problem executing `%s`.%s\n"
"%s"
msgstr ""

#: ../tails_installer/utils.py:124
msgid "Could not open device for writing."
msgstr ""

#: ../data/tails-installer.ui.h:1
msgid "Installation Instructions"
msgstr ""

#: ../data/tails-installer.ui.h:2
msgid "Clone the current Tails"
msgstr ""

#: ../data/tails-installer.ui.h:3
msgid "Use a downloaded Tails ISO image"
msgstr ""

#: ../data/tails-installer.ui.h:4
msgid "Select a distribution to download:"
msgstr ""

#: ../data/tails-installer.ui.h:5
msgid "Target USB stick:"
msgstr ""

#: ../data/tails-installer.ui.h:6
msgid "Reinstall (delete all data)"
msgstr ""

#: ../data/tails-installer.ui.h:7
msgid "Install Tails"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:1
msgid ""
"To run Tails Installer you need an ISO image which can be downloaded from "
"the Tails website: <a "
"href=\"https://tails.boum.org/download/\">https://tails.boum.org/download/</a>"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:2
msgid "Install"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:3
msgid "• Install Tails on a new USB stick."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:4
msgid "• The USB stick that you install on is formatted and all data is lost."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:5
msgid "Upgrade"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:6
msgid "• Upgrade a Tails USB stick to the version of an ISO image."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:7
msgid ""
"• The encrypted persistent storage of the Tails USB stick that you upgrade "
"is preserved."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:8
msgid ""
"Need help? Read the <a "
"href=\"https://tails.boum.org/doc/first_steps/installation/\">documentation</a>"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:9
msgid "Install by cloning"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:10
msgid ""
"• Install Tails on another USB stick by copying the Tails system that you "
"are currently using."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:11
msgid ""
"• The encrypted persistent storage of the Tails USB stick that you are "
"currently using is not copied."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:12
msgid "Upgrade by cloning"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:13
msgid ""
"• Upgrade another Tails USB stick to the same version of Tails that you are "
"currently using."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:14
msgid "Upgrade from ISO"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:15
msgid "• Upgrade another Tails USB stick to the version of an ISO image."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:16
msgid ""
"Need help? Read the <a "
"href=\"file:///usr/share/doc/tails/website/doc/first_steps/installation.en.html\">documentation</a>"
msgstr ""
