# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# brendanyan <yan.brendan@gmail.com>, 2014
# Casper Li <casper.hk@hotmail.com>, 2013
# coco coco, 2017
# 大圈洋蔥, 2016
# Casper Li <casper.hk@hotmail.com>, 2013
# ronnietse <tseronnie@ymail.com>, 2014
# ronnietse <tseronnie@ymail.com>, 2014
# brendanyan <yan.brendan@gmail.com>, 2014
# 大圈洋蔥, 2016
# 大圈洋蔥, 2016
msgid ""
msgstr ""
"Project-Id-Version: Tor Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-10-17 13:11+0200\n"
"PO-Revision-Date: 2018-10-17 14:51+0000\n"
"Last-Translator: erinm\n"
"Language-Team: Chinese (Hong Kong) (http://www.transifex.com/otf/torproject/language/zh_HK/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: zh_HK\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../tails_installer/creator.py:100
msgid "You must run this application as root"
msgstr "你須以root身份執行此應用程式"

#: ../tails_installer/creator.py:146
msgid "Extracting live image to the target device..."
msgstr "正在解壓縮即時映像檔到目標設備…"

#: ../tails_installer/creator.py:153
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr "以每秒%(speed)d MB嘅速度寫入裝置"

#: ../tails_installer/creator.py:296
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr "執行下列指令時發生錯誤：%(command)s。\n詳細嘅錯誤記錄已寫入到%(filename)s。"

#: ../tails_installer/creator.py:315
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr "驗證LiveCD映像檔嘅SHA1總和碼…"

#: ../tails_installer/creator.py:319
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr "驗證LiveCD映像檔嘅SHA256總和碼…"

#: ../tails_installer/creator.py:335
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr "錯誤：你Live CD嘅SHA1無效。你可使用 --noverify 參數嚟執行此程式以略過此驗證檢查。"

#: ../tails_installer/creator.py:341
msgid "Unknown ISO, skipping checksum verification"
msgstr "未知的ISO，略過總和碼驗證"

#: ../tails_installer/creator.py:353
#, python-format
msgid ""
"Not enough free space on device.\n"
"%dMB ISO + %dMB overlay > %dMB free space"
msgstr "裝置上嘅可用空間唔夠。\n%dMB「ISO」加上%dMB「覆蓋」大於%dMB可用空間"

#: ../tails_installer/creator.py:360
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "建立%sMB持續覆蓋"

#: ../tails_installer/creator.py:421
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr "無法複製%(infile)s到%(outfile)s：%(message)s"

#: ../tails_installer/creator.py:435
msgid "Removing existing Live OS"
msgstr "移除現存嘅Live OS"

#: ../tails_installer/creator.py:444 ../tails_installer/creator.py:456
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr "無法以chmod更改權限%(file)s：%(message)s"

#: ../tails_installer/creator.py:449
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr "無法由先前嘅LiveOS移除檔案：%(message)s"

#: ../tails_installer/creator.py:462
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr "無法由先前嘅LiveOS移除目錄：%(message)s"

#: ../tails_installer/creator.py:510
#, python-format
msgid "Cannot find device %s"
msgstr "搵唔到裝置%s"

#: ../tails_installer/creator.py:711
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr "無法寫入%(device)s，略過。"

#: ../tails_installer/creator.py:741
#, python-format
msgid ""
"Some partitions of the target device %(device)s are mounted. They will be "
"unmounted before starting the installation process."
msgstr "目標裝置%(device)s中一啲分割區已掛接。佢哋將於開始安裝過程前被卸載。"

#: ../tails_installer/creator.py:784 ../tails_installer/creator.py:1008
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr "未知嘅檔案系統。你嘅裝置可能須重新格式化。"

#: ../tails_installer/creator.py:787 ../tails_installer/creator.py:1011
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "唔支援嘅檔案系統：%s"

#: ../tails_installer/creator.py:805
#, python-format
msgid "Unknown GLib exception while trying to mount device: %(message)s"
msgstr "嘗試安裝設備時出現未知的GLib異常： %(message)s"

#: ../tails_installer/creator.py:810
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr "無法掛接裝置：%(message)s"

#: ../tails_installer/creator.py:815
msgid "No mount points found"
msgstr "搵唔到掛接點"

#: ../tails_installer/creator.py:826
#, python-format
msgid "Entering unmount_device for '%(device)s'"
msgstr "進入未掛接裝置「%(device)s」"

#: ../tails_installer/creator.py:836
#, python-format
msgid "Unmounting mounted filesystems on '%(device)s'"
msgstr "正在卸載掛接係%(device)s上嘅檔案系統"

#: ../tails_installer/creator.py:840
#, python-format
msgid "Unmounting '%(udi)s' on '%(device)s'"
msgstr "正在卸載%(device)s嘅%(udi)s"

#: ../tails_installer/creator.py:851
#, python-format
msgid "Mount %s exists after unmounting"
msgstr "取消掛接後%s掛接仍存在"

#: ../tails_installer/creator.py:864
#, python-format
msgid "Partitioning device %(device)s"
msgstr "分割區裝置%(device)s"

#: ../tails_installer/creator.py:993
#, python-format
msgid "Unsupported device '%(device)s', please report a bug."
msgstr "唔支援嘅裝置%(device)s，請報告錯誤。"

#: ../tails_installer/creator.py:996
msgid "Trying to continue anyway."
msgstr "無論如何仍嘗試繼續。"

#: ../tails_installer/creator.py:1005 ../tails_installer/creator.py:1401
msgid "Verifying filesystem..."
msgstr "正在驗證檔案系統…"

#: ../tails_installer/creator.py:1029
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr "無法更改磁碟區標籤：%(message)s"

#: ../tails_installer/creator.py:1034 ../tails_installer/creator.py:1434
msgid "Installing bootloader..."
msgstr "安裝Bootloader…"

#: ../tails_installer/creator.py:1061
#, python-format
msgid "Could not find the '%s' COM32 module"
msgstr "找不到'%s'COM32模塊"

#: ../tails_installer/creator.py:1069 ../tails_installer/creator.py:1452
#, python-format
msgid "Removing %(file)s"
msgstr "移除%(file)s"

#: ../tails_installer/creator.py:1183
#, python-format
msgid "%s already bootable"
msgstr "%s已可開機"

#: ../tails_installer/creator.py:1203
msgid "Unable to find partition"
msgstr "搵唔到分割區"

#: ../tails_installer/creator.py:1226
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr "將%(device)s格式化成Fat32格式"

#: ../tails_installer/creator.py:1286
msgid "Could not find syslinux' gptmbr.bin"
msgstr "找不到syslinux' gptmbr.bin"

#: ../tails_installer/creator.py:1299
#, python-format
msgid "Reading extracted MBR from %s"
msgstr "從MBR中讀取%s"

#: ../tails_installer/creator.py:1303
#, python-format
msgid "Could not read the extracted MBR from %(path)s"
msgstr "無法讀取所選取的MBR%(path)s"

#: ../tails_installer/creator.py:1316 ../tails_installer/creator.py:1317
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr "重設%s的MBR主開機紀錄"

#: ../tails_installer/creator.py:1322
msgid "Drive is a loopback, skipping MBR reset"
msgstr "磁碟迴送，略過MBR重設"

#: ../tails_installer/creator.py:1326 ../tails_installer/creator.py:1580
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr "計算%s嘅SHA1"

#: ../tails_installer/creator.py:1351
msgid "Synchronizing data on disk..."
msgstr "同步磁碟上嘅資料…"

#: ../tails_installer/creator.py:1393
msgid "Error probing device"
msgstr "探測裝置失敗"

#: ../tails_installer/creator.py:1395
msgid "Unable to find any supported device"
msgstr "搵唔到任何支援嘅裝置"

#: ../tails_installer/creator.py:1405
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr "請確認USB磁碟已插入，並使用FAT進行格式化"

#: ../tails_installer/creator.py:1408
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "唔支援嘅檔案系統：%s\n請進行備份並使用FAT嚟格式化USB磁碟。"

#: ../tails_installer/creator.py:1475
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr "無法取得Win32_LogicalDisk；win32com查詢未傳回任何結果"

#: ../tails_installer/creator.py:1528
msgid "Cannot find"
msgstr "搵唔到"

#: ../tails_installer/creator.py:1529
msgid ""
"Make sure to extract the entire tails-installer zip file before running this"
" program."
msgstr "執行此程式前請先解壓縮整個libusb-creator zip檔案。"

#: ../tails_installer/gui.py:69
#, python-format
msgid "Unknown release: %s"
msgstr "未知嘅發行版本：%s"

#: ../tails_installer/gui.py:73
#, python-format
msgid "Downloading %s..."
msgstr "下載%s…"

#: ../tails_installer/gui.py:213
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "錯誤：無法設定標籤或取得你設備嘅UUID。無法繼續。"

#: ../tails_installer/gui.py:260
#, python-format
msgid "Installation complete! (%s)"
msgstr "安裝完成！(%s)"

#: ../tails_installer/gui.py:265
msgid "Tails installation failed!"
msgstr "Tails安裝失敗！"

#: ../tails_installer/gui.py:361
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr "警告：此工具需以系統管理員身份執行。請對圖示撳滑鼠右鍵後點選內容，喺相容性分頁下，選取「以系統管理員身份執行此程式」。"

#: ../tails_installer/gui.py:373
msgid "Tails Installer"
msgstr "Tails安裝程序"

#: ../tails_installer/gui.py:423 ../data/tails-installer.ui.h:2
msgid "Clone the current Tails"
msgstr ""

#: ../tails_installer/gui.py:430 ../data/tails-installer.ui.h:3
msgid "Use a downloaded Tails ISO image"
msgstr ""

#: ../tails_installer/gui.py:467 ../tails_installer/gui.py:788
msgid "Upgrade"
msgstr "更新"

#: ../tails_installer/gui.py:469
msgid "Manual Upgrade Instructions"
msgstr ""

#: ../tails_installer/gui.py:471
msgid "https://tails.boum.org/upgrade/"
msgstr ""

#: ../tails_installer/gui.py:479 ../tails_installer/gui.py:700
#: ../tails_installer/gui.py:765 ../data/tails-installer.ui.h:7
msgid "Install"
msgstr ""

#: ../tails_installer/gui.py:482 ../data/tails-installer.ui.h:1
msgid "Installation Instructions"
msgstr ""

#: ../tails_installer/gui.py:484
msgid "https://tails.boum.org/install/"
msgstr ""

#: ../tails_installer/gui.py:490
#, python-format
msgid "%(size)s %(vendor)s %(model)s device (%(device)s)"
msgstr ""

#: ../tails_installer/gui.py:502
msgid "No ISO image selected"
msgstr ""

#: ../tails_installer/gui.py:503
msgid "Please select a Tails ISO image."
msgstr ""

#: ../tails_installer/gui.py:545
msgid "No device suitable to install Tails could be found"
msgstr ""

#: ../tails_installer/gui.py:547
#, python-format
msgid "Please plug a USB flash drive or SD card of at least %0.1f GB."
msgstr "請插入至少%0.1fGB的USB快閃隨身碟或SD卡。"

#: ../tails_installer/gui.py:581
#, python-format
msgid ""
"The USB stick \"%(pretty_name)s\" is configured as non-removable by its "
"manufacturer and Tails will fail to start on it. Please try installing on a "
"different model."
msgstr "USB快閃隨身碟\"%(pretty_name)s\"由其製造商設計為不可拆卸，並且Tails將無法啟動它。請嘗試安裝在其他型號上。"

#: ../tails_installer/gui.py:591
#, python-format
msgid ""
"The device \"%(pretty_name)s\" is too small to install Tails (at least "
"%(size)s GB is required)."
msgstr "「%(pretty_name)s」設備嘅容量太小，無法安裝Tails(至少需要%(size)s GB嘅空間)。"

#: ../tails_installer/gui.py:604
#, python-format
msgid ""
"To upgrade device \"%(pretty_name)s\" from this Tails, you need to use a downloaded Tails ISO image:\n"
"https://tails.boum.org/install/download"
msgstr ""

#: ../tails_installer/gui.py:625
msgid "An error happened while installing Tails"
msgstr "安裝Tails時發生錯誤"

#: ../tails_installer/gui.py:637
msgid "Refreshing releases..."
msgstr "正在重新整理版本…"

#: ../tails_installer/gui.py:642
msgid "Releases updated!"
msgstr "版本已更新！"

#: ../tails_installer/gui.py:695
msgid "Installation complete!"
msgstr "安裝完成！"

#: ../tails_installer/gui.py:711
msgid "Cancel"
msgstr "取消"

#: ../tails_installer/gui.py:747
msgid "Unable to mount device"
msgstr "無法掛接裝置"

#: ../tails_installer/gui.py:754 ../tails_installer/gui.py:787
msgid "Confirm the target USB stick"
msgstr ""

#: ../tails_installer/gui.py:755
#, python-format
msgid ""
"%(size)s %(vendor)s %(model)s device (%(device)s)\n"
"\n"
"All data on this USB stick will be lost."
msgstr ""

#: ../tails_installer/gui.py:774
#, python-format
msgid "%(parent_size)s %(vendor)s %(model)s device (%(device)s)"
msgstr ""

#: ../tails_installer/gui.py:782
msgid ""
"\n"
"\n"
"The persistent storage on this USB stick will be preserved."
msgstr ""

#: ../tails_installer/gui.py:783
#, python-format
msgid "%(description)s%(persistence_message)s"
msgstr ""

#: ../tails_installer/gui.py:826
msgid "Download complete!"
msgstr "下載完成！"

#: ../tails_installer/gui.py:830
msgid "Download failed: "
msgstr "下載失敗："

#: ../tails_installer/gui.py:831
msgid "You can try again to resume your download"
msgstr "可嘗試回復下載"

#: ../tails_installer/gui.py:839
msgid ""
"The selected file is unreadable. Please fix its permissions or select "
"another file."
msgstr "所選檔案無法讀取。請修正其權限或選取另一檔案。"

#: ../tails_installer/gui.py:845
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr "無法使用所選檔案。如你將ISO移動到磁碟根目錄下(例如：C:\\)，你可能會好運一啲"

#: ../tails_installer/gui.py:851
#, python-format
msgid "%(filename)s selected"
msgstr "已選取%(filename)s"

#: ../tails_installer/source.py:28
msgid "Unable to find LiveOS on ISO"
msgstr "無法在ISO上找到LiveOS"

#: ../tails_installer/source.py:34
#, python-format
msgid "Could not guess underlying block device: %s"
msgstr ""

#: ../tails_installer/source.py:49
#, python-format
msgid ""
"There was a problem executing `%s`.\n"
"%s\n"
"%s"
msgstr ""

#: ../tails_installer/source.py:63
#, python-format
msgid "'%s' does not exist"
msgstr ""

#: ../tails_installer/source.py:65
#, python-format
msgid "'%s' is not a directory"
msgstr ""

#: ../tails_installer/source.py:75
#, python-format
msgid "Skipping '%(filename)s'"
msgstr ""

#: ../tails_installer/utils.py:44
#, python-format
msgid ""
"There was a problem executing `%s`.%s\n"
"%s"
msgstr ""

#: ../tails_installer/utils.py:124
msgid "Could not open device for writing."
msgstr ""

#: ../data/tails-installer.ui.h:4
msgid "Select a distribution to download:"
msgstr ""

#: ../data/tails-installer.ui.h:5
msgid "Target USB stick:"
msgstr ""

#: ../data/tails-installer.ui.h:6
msgid "Reinstall (delete all data)"
msgstr ""
