# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# bassmax, 2014
# Alex <z-transifex@demollien.net>, 2014-2015
# AO <ao@localizationlab.org>, 2018
# arpalord <inactive+arpalord@transifex.com>, 2012
# 5boro <bastien@pontet.eu>, 2015
# BitingBird <bitingbird@riseup.net>, 2015
# Charles-Antoine Couret, 2009
# Charles-Antoine Couret <cacouret@wanadoo.fr>, 2009
# Emmanuel Simond <emmanuel.simond@gmail.com>, 2014
# Eric lassauge <lassauge {AT} users {dot} sourceforge {dot} net>, 2010
# AO <ao@localizationlab.org>, 2017-2018
# AO <ao@localizationlab.org>, 2016
# Gwennole Hangard <gwennole.hangard@gmail.com>, 2015
# Jean-Yves Toumit <saiolar-c@yahoo.fr>, 2013
# Martin Trigaux, 2015
# Onizuka, 2013
# Michael Ughetto <telimektar1er@gmail.com>, 2008
# Onizuka, 2013
# Martin-Gomez Pablo <pablomg+transifex@eskapa.be>, 2008
# themen <themen2004@gmail.com>, 2014
# AO <ao@localizationlab.org>, 2015
msgid ""
msgstr ""
"Project-Id-Version: Tor Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-10-17 13:11+0200\n"
"PO-Revision-Date: 2018-10-18 21:32+0000\n"
"Last-Translator: AO <ao@localizationlab.org>\n"
"Language-Team: French (http://www.transifex.com/otf/torproject/language/fr/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: fr\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ../tails_installer/creator.py:100
msgid "You must run this application as root"
msgstr "Vous devez exécuter cette application en tant que superutilisateur"

#: ../tails_installer/creator.py:146
msgid "Extracting live image to the target device..."
msgstr "Extraction de l’image autonome vers le périphérique cible…"

#: ../tails_installer/creator.py:153
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr "Écrit sur le périphérique à %(speed)d Mo/sec"

#: ../tails_installer/creator.py:296
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr "Un problème est survenu lors de l’exécution de la commande suivante : « %(command)s »\nUn journal d’erreurs plus détaillé a été écrit dans le fichier « %(filename)s »."

#: ../tails_installer/creator.py:315
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr "Vérification de la somme de contrôle SHA1 de l’image du CD autonome…"

#: ../tails_installer/creator.py:319
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr "Vérification de la somme de contrôle SHA256 de l’image du CD autonome…"

#: ../tails_installer/creator.py:335
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr "Erreur : le SHA1 de votre CD autonome est invalide. Vous pouvez exécuter ce programme avec l’argument « --noverify » pour contourner cette vérification."

#: ../tails_installer/creator.py:341
msgid "Unknown ISO, skipping checksum verification"
msgstr "ISO inconnue, omission de la vérification de la somme de contrôle"

#: ../tails_installer/creator.py:353
#, python-format
msgid ""
"Not enough free space on device.\n"
"%dMB ISO + %dMB overlay > %dMB free space"
msgstr "Pas assez d’espace libre sur le périphérique.\nISO de %d Mo + persistance de %d Mo persistance > %d Mo d’espace libre"

#: ../tails_installer/creator.py:360
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "Création du stockage persistant de %s Mo"

#: ../tails_installer/creator.py:421
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr "Impossible de copier %(infile)s vers %(outfile)s : %(message)s"

#: ../tails_installer/creator.py:435
msgid "Removing existing Live OS"
msgstr "Suppression du SE autonome existant"

#: ../tails_installer/creator.py:444 ../tails_installer/creator.py:456
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr "chmod impossible %(file)s : %(message)s"

#: ../tails_installer/creator.py:449
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr "Impossible d’enlever le fichier du SE autonome précédent : %(message)s"

#: ../tails_installer/creator.py:462
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr "Impossible d’enlever le répertoire du SE autonome précédent : %(message)s"

#: ../tails_installer/creator.py:510
#, python-format
msgid "Cannot find device %s"
msgstr "Le périphérique %s est introuvable"

#: ../tails_installer/creator.py:711
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr "Impossible d’écrire sur %(device)s, passage à l’étape suivante."

#: ../tails_installer/creator.py:741
#, python-format
msgid ""
"Some partitions of the target device %(device)s are mounted. They will be "
"unmounted before starting the installation process."
msgstr "Certaines partitions du périphérique cible %(device)s sont montées. Elles seront démontées avant de démarrer le processus d’installation."

#: ../tails_installer/creator.py:784 ../tails_installer/creator.py:1008
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr "Le système de fichiers est inconnu. Il est possible qu’il faille reformater votre périphérique."

#: ../tails_installer/creator.py:787 ../tails_installer/creator.py:1011
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "Système de fichiers non pris en charge : %s"

#: ../tails_installer/creator.py:805
#, python-format
msgid "Unknown GLib exception while trying to mount device: %(message)s"
msgstr "Exception GLib inconnue en tentant de monter le périphérique : %(message)s"

#: ../tails_installer/creator.py:810
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr "Impossible de monter le périphérique : %(message)s"

#: ../tails_installer/creator.py:815
msgid "No mount points found"
msgstr "Aucun point de montage n’a été trouvé"

#: ../tails_installer/creator.py:826
#, python-format
msgid "Entering unmount_device for '%(device)s'"
msgstr "Saisie de unmount_device pour « %(device)s »"

#: ../tails_installer/creator.py:836
#, python-format
msgid "Unmounting mounted filesystems on '%(device)s'"
msgstr "Démontage des systèmes de fichiers montés sur « %(device)s »"

#: ../tails_installer/creator.py:840
#, python-format
msgid "Unmounting '%(udi)s' on '%(device)s'"
msgstr "Démontage de « %(udi)s » sur « %(device)s »"

#: ../tails_installer/creator.py:851
#, python-format
msgid "Mount %s exists after unmounting"
msgstr "Le montage %s existe après démontage"

#: ../tails_installer/creator.py:864
#, python-format
msgid "Partitioning device %(device)s"
msgstr "Partitionnement du périphérique %(device)s"

#: ../tails_installer/creator.py:993
#, python-format
msgid "Unsupported device '%(device)s', please report a bug."
msgstr "Le périphérique « %(device)s » n’est pas pris en charge, veuillez signaler le bogue."

#: ../tails_installer/creator.py:996
msgid "Trying to continue anyway."
msgstr "Nous tentons de continuer quand même."

#: ../tails_installer/creator.py:1005 ../tails_installer/creator.py:1401
msgid "Verifying filesystem..."
msgstr "Vérification du système de fichiers…"

#: ../tails_installer/creator.py:1029
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr "Impossible de changer l’étiquette du volume : %(message)s"

#: ../tails_installer/creator.py:1034 ../tails_installer/creator.py:1434
msgid "Installing bootloader..."
msgstr "Installation du chargeur de démarrage…"

#: ../tails_installer/creator.py:1061
#, python-format
msgid "Could not find the '%s' COM32 module"
msgstr "Impossible de trouver le module COM32 « %s »"

#: ../tails_installer/creator.py:1069 ../tails_installer/creator.py:1452
#, python-format
msgid "Removing %(file)s"
msgstr "Suppression de %(file)s"

#: ../tails_installer/creator.py:1183
#, python-format
msgid "%s already bootable"
msgstr "%s est déjà amorçable"

#: ../tails_installer/creator.py:1203
msgid "Unable to find partition"
msgstr "Impossible de trouver la partition"

#: ../tails_installer/creator.py:1226
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr "Formatage de %(device)s en FAT32"

#: ../tails_installer/creator.py:1286
msgid "Could not find syslinux' gptmbr.bin"
msgstr "Impossible de trouver gptmbr.bin de SYSLYNUX"

#: ../tails_installer/creator.py:1299
#, python-format
msgid "Reading extracted MBR from %s"
msgstr "Lecture de l’enregistrement d’amorçage maître extrait de %s"

#: ../tails_installer/creator.py:1303
#, python-format
msgid "Could not read the extracted MBR from %(path)s"
msgstr "Impossible de lire l’enregistrement d’amorçage maître extrait de %(path)s"

#: ../tails_installer/creator.py:1316 ../tails_installer/creator.py:1317
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr "Réinitialisation de l’enregistrement d’amorçage maître de %s"

#: ../tails_installer/creator.py:1322
msgid "Drive is a loopback, skipping MBR reset"
msgstr "Le périphérique est une boucle avec retour, omission de la réinitialisation de l’enregistrement d’amorçage maître"

#: ../tails_installer/creator.py:1326 ../tails_installer/creator.py:1580
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr "Calcul du SHA1 de %s"

#: ../tails_installer/creator.py:1351
msgid "Synchronizing data on disk..."
msgstr "Synchronisation des données sur le disque…"

#: ../tails_installer/creator.py:1393
msgid "Error probing device"
msgstr "Erreur de sondage du périphérique"

#: ../tails_installer/creator.py:1395
msgid "Unable to find any supported device"
msgstr "Aucun périphérique pris en charge n’a été trouvé"

#: ../tails_installer/creator.py:1405
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr "Assurez-vous que votre clé USB est branchée et formatée avec le système de fichiers FAT"

#: ../tails_installer/creator.py:1408
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "Système de fichiers non pris en charge : %s\nVeuillez sauvegarder votre clé USB et la formater avec le système de fichiers FAT."

#: ../tails_installer/creator.py:1475
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr "Impossible d’obtenir Win32_LogicalDisk ; la requête win32com n’a retourné aucun résultat."

#: ../tails_installer/creator.py:1528
msgid "Cannot find"
msgstr "Introuvable"

#: ../tails_installer/creator.py:1529
msgid ""
"Make sure to extract the entire tails-installer zip file before running this"
" program."
msgstr "Assurez-vous d’extraire le fichier zip entier du programme d’installation Tails avant d’exécuter ce programme."

#: ../tails_installer/gui.py:69
#, python-format
msgid "Unknown release: %s"
msgstr "Version inconnue : %s"

#: ../tails_installer/gui.py:73
#, python-format
msgid "Downloading %s..."
msgstr "Téléchargement de %s…"

#: ../tails_installer/gui.py:213
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "Erreur : impossible de définir l’étiquette ou d’obtenir l’UUID de votre périphérique. Impossible de poursuivre."

#: ../tails_installer/gui.py:260
#, python-format
msgid "Installation complete! (%s)"
msgstr "L’installation est terminée ! (%s)"

#: ../tails_installer/gui.py:265
msgid "Tails installation failed!"
msgstr "L’installation de Tails a échoué !"

#: ../tails_installer/gui.py:361
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr "Avertissement : cet outil doit être exécuté en tant qu’administrateur. Pour ce faire, cliquer sur l’icône et ouvrir les Propriétés. Sous l’onglet Compatibilité, cocher « Exécuter ce programme en tant qu’administrateur »."

#: ../tails_installer/gui.py:373
msgid "Tails Installer"
msgstr "Programme d’installation Tails"

#: ../tails_installer/gui.py:423 ../data/tails-installer.ui.h:2
msgid "Clone the current Tails"
msgstr "Cloner le Tails actuel"

#: ../tails_installer/gui.py:430 ../data/tails-installer.ui.h:3
msgid "Use a downloaded Tails ISO image"
msgstr "Utiliser une image ISO de Tails téléchargée"

#: ../tails_installer/gui.py:467 ../tails_installer/gui.py:788
msgid "Upgrade"
msgstr "Mettre à niveau"

#: ../tails_installer/gui.py:469
msgid "Manual Upgrade Instructions"
msgstr "Instructions de mise à niveau manuelle"

#: ../tails_installer/gui.py:471
msgid "https://tails.boum.org/upgrade/"
msgstr "https://tails.boum.org/upgrade/"

#: ../tails_installer/gui.py:479 ../tails_installer/gui.py:700
#: ../tails_installer/gui.py:765 ../data/tails-installer.ui.h:7
msgid "Install"
msgstr "Installer"

#: ../tails_installer/gui.py:482 ../data/tails-installer.ui.h:1
msgid "Installation Instructions"
msgstr "Instructions d’installation"

#: ../tails_installer/gui.py:484
msgid "https://tails.boum.org/install/"
msgstr "https://tails.boum.org/install/"

#: ../tails_installer/gui.py:490
#, python-format
msgid "%(size)s %(vendor)s %(model)s device (%(device)s)"
msgstr "%(size)s %(vendor)s %(model)s périphérique (%(device)s)"

#: ../tails_installer/gui.py:502
msgid "No ISO image selected"
msgstr "Aucune image ISO n’a été sélectionnée"

#: ../tails_installer/gui.py:503
msgid "Please select a Tails ISO image."
msgstr "Veuillez sélectionner une image ISO de Tails."

#: ../tails_installer/gui.py:545
msgid "No device suitable to install Tails could be found"
msgstr "Aucun périphérique compatible n’a été trouvé pour installer Tails"

#: ../tails_installer/gui.py:547
#, python-format
msgid "Please plug a USB flash drive or SD card of at least %0.1f GB."
msgstr "Veuillez connecter une clé USB ou une carte SD d’au moins %0.1f Go."

#: ../tails_installer/gui.py:581
#, python-format
msgid ""
"The USB stick \"%(pretty_name)s\" is configured as non-removable by its "
"manufacturer and Tails will fail to start on it. Please try installing on a "
"different model."
msgstr "La clé USB « %(pretty_name)s » est configurée comme non amovible par son fabricant et le démarrage de Tails échouera sur cette clé. Veuillez tenter de l’installer sur un modèle différent."

#: ../tails_installer/gui.py:591
#, python-format
msgid ""
"The device \"%(pretty_name)s\" is too small to install Tails (at least "
"%(size)s GB is required)."
msgstr "Le dispositif « %(pretty_name)s » est trop petit pour installer Tails (au moins %(size)s Go sont exigés)."

#: ../tails_installer/gui.py:604
#, python-format
msgid ""
"To upgrade device \"%(pretty_name)s\" from this Tails, you need to use a downloaded Tails ISO image:\n"
"https://tails.boum.org/install/download"
msgstr "Pour mettre à niveau l’appareil « %(pretty_name)s » à partir de ce Tails, vous devez utiliser une image ISO Tails téléchargée :\nhttps://tails.boum.org/install/download"

#: ../tails_installer/gui.py:625
msgid "An error happened while installing Tails"
msgstr "Une erreur est survenue lors de l’installation de Tails"

#: ../tails_installer/gui.py:637
msgid "Refreshing releases..."
msgstr "Actualisation des versions…"

#: ../tails_installer/gui.py:642
msgid "Releases updated!"
msgstr "Les versions ont été mises à jour !"

#: ../tails_installer/gui.py:695
msgid "Installation complete!"
msgstr "L’installation est terminée !"

#: ../tails_installer/gui.py:711
msgid "Cancel"
msgstr "Annuler"

#: ../tails_installer/gui.py:747
msgid "Unable to mount device"
msgstr "Impossible de monter le périphérique"

#: ../tails_installer/gui.py:754 ../tails_installer/gui.py:787
msgid "Confirm the target USB stick"
msgstr "Confirmer la clé USB cible"

#: ../tails_installer/gui.py:755
#, python-format
msgid ""
"%(size)s %(vendor)s %(model)s device (%(device)s)\n"
"\n"
"All data on this USB stick will be lost."
msgstr "%(size)s %(vendor)s %(model)s périphérique (%(device)s)\n\nToutes les données sur ce périphérique seront perdues."

#: ../tails_installer/gui.py:774
#, python-format
msgid "%(parent_size)s %(vendor)s %(model)s device (%(device)s)"
msgstr "%(parent_size)s %(vendor)s %(model)s périphérique (%(device)s)"

#: ../tails_installer/gui.py:782
msgid ""
"\n"
"\n"
"The persistent storage on this USB stick will be preserved."
msgstr "\n\nL’espace de stockage persistant de cette clé USB sera préservé."

#: ../tails_installer/gui.py:783
#, python-format
msgid "%(description)s%(persistence_message)s"
msgstr "%(description)s%(persistence_message)s"

#: ../tails_installer/gui.py:826
msgid "Download complete!"
msgstr "Le téléchargement est terminé !"

#: ../tails_installer/gui.py:830
msgid "Download failed: "
msgstr "Échec de téléchargement : "

#: ../tails_installer/gui.py:831
msgid "You can try again to resume your download"
msgstr "Vous pouvez ressayer pour reprendre votre téléchargement"

#: ../tails_installer/gui.py:839
msgid ""
"The selected file is unreadable. Please fix its permissions or select "
"another file."
msgstr "Le fichier sélectionné est illisible. Veuillez changer ses droits ou sélectionner un autre fichier."

#: ../tails_installer/gui.py:845
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr "Impossible d’utiliser le fichier sélectionné.Il est possible que vous ayez plus de chance en déplaçant l’ISO sur la racine de votre disque (c.-à-d. : C:\\)"

#: ../tails_installer/gui.py:851
#, python-format
msgid "%(filename)s selected"
msgstr "%(filename)s sélectionné"

#: ../tails_installer/source.py:28
msgid "Unable to find LiveOS on ISO"
msgstr "Impossible de trouver le SE autonome sur l’ISO"

#: ../tails_installer/source.py:34
#, python-format
msgid "Could not guess underlying block device: %s"
msgstr "Impossible de deviner le périphérique de blocs sous-jacent : %s"

#: ../tails_installer/source.py:49
#, python-format
msgid ""
"There was a problem executing `%s`.\n"
"%s\n"
"%s"
msgstr "Un problème est survenu lors de l’exécution de `%s`.\n%s\n%s"

#: ../tails_installer/source.py:63
#, python-format
msgid "'%s' does not exist"
msgstr "« %s » n’existe pas"

#: ../tails_installer/source.py:65
#, python-format
msgid "'%s' is not a directory"
msgstr "« %s » n’est pas un répertoire"

#: ../tails_installer/source.py:75
#, python-format
msgid "Skipping '%(filename)s'"
msgstr "'%(filename)s' est ignoré"

#: ../tails_installer/utils.py:44
#, python-format
msgid ""
"There was a problem executing `%s`.%s\n"
"%s"
msgstr "Un problème est survenu lors de l’exécution de `%s`.%s\n%s"

#: ../tails_installer/utils.py:124
msgid "Could not open device for writing."
msgstr "Impossible d’ouvrir le périphérique en écriture."

#: ../data/tails-installer.ui.h:4
msgid "Select a distribution to download:"
msgstr "Choisir une version à télécharger :"

#: ../data/tails-installer.ui.h:5
msgid "Target USB stick:"
msgstr "Clé USB cible :"

#: ../data/tails-installer.ui.h:6
msgid "Reinstall (delete all data)"
msgstr "Réinstaller (supprimer toutes les données)"
