# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Анатолий Гуськов <anatoliy.guskov@gmail.com>, 2009
# Andrey, 2016
# Andrey, 2017
# Антон Толмачев <a.tolmachev@richart-consalt.ru>, 2015
# Den Arefyev <>, 2012
# Denis Denis <stereodenis@gmail.com>, 2014
# Eugene, 2013
# Елисеев Дмитрий <inactive+ddark008@transifex.com>, 2012
# Иван Лапенков, 2015
# jujjer <jujjer@gmail.com>, 2013
# Misha Dyachuk <Wikia@scryptmail.com>, 2016
# Oul Gocke <beandonlybe@yandex.ru>, 2013-2014
# Roberto Brigante, 2017
# Sergey Briskin, 2014
# tavarysh <tavarysh@riseup.net>, 2013
# Vladimir.Serykh <Vladimir.Serykh@extenza-studio.ru>, 2015
# vlasok <vlasok1987@yandex.ru>, 2012
# Yulia <ypoyarko@redhat.com>, 2009
# Uho Lot <yavinav@gmail.com>, 2016
# pistenrammler <inactive+pistenrammler@transifex.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: The Tor Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-09-14 14:52+0200\n"
"PO-Revision-Date: 2017-09-19 14:12+0000\n"
"Last-Translator: carolyn <carolyn@anhalt.org>\n"
"Language-Team: Russian (http://www.transifex.com/otf/torproject/language/ru/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ru\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);\n"

#: ../tails_installer/creator.py:101
msgid "You must run this application as root"
msgstr "Нужно запускать это приложение из-под root"

#: ../tails_installer/creator.py:147
msgid "Extracting live image to the target device..."
msgstr "Извлечение живого образа на целевое устройство..."

#: ../tails_installer/creator.py:154
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr "Записано на скорости %(speed)d МБ/сек"

#: ../tails_installer/creator.py:184
msgid "Setting up OLPC boot file..."
msgstr "Настройка загрузочного файла OLPC..."

#: ../tails_installer/creator.py:321
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr "Ошибка выполнения команды: `%(command)s`.\nПодробный журнал ошибок сохранен в  '%(filename)s'."

#: ../tails_installer/creator.py:340
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr "Проверка SHA1 LiveCD образа..."

#: ../tails_installer/creator.py:344
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr "Проверка SHA256 LiveCD образа..."

#: ../tails_installer/creator.py:360
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr "Ошибка: Неверное SHA1 вашего Live CD образа.  Вы можете запустить программу с аргументом --noverify, чтобы пропустить проверку."

#: ../tails_installer/creator.py:366
msgid "Unknown ISO, skipping checksum verification"
msgstr "Неизвестный ISO, проверка контрольной суммы пропущена"

#: ../tails_installer/creator.py:377
#, python-format
msgid ""
"Not enough free space on device.\n"
"%dMB ISO + %dMB overlay > %dMB free space"
msgstr "Недостаточно места на устройстве.\n%dMB ISO + %dMB постоянное хранилище > %dMB свободного места"

#: ../tails_installer/creator.py:384
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "Создание %sМБ постоянного хранилища"

#: ../tails_installer/creator.py:445
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr "Невозможно копировать %(infile)s в %(outfile)s: %(message)s"

#: ../tails_installer/creator.py:459
msgid "Removing existing Live OS"
msgstr "Удаление существующей Live OS"

#: ../tails_installer/creator.py:468 ../tails_installer/creator.py:479
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr "Невозможно chmod %(file)s: %(message)s"

#: ../tails_installer/creator.py:472
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr "Невозможно удалить файл из предыдущей LiveOS: %(message)s"

#: ../tails_installer/creator.py:484
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr "Невозможно удалить директорию из предыдущей LiveOS: %(message)s"

#: ../tails_installer/creator.py:532
#, python-format
msgid "Cannot find device %s"
msgstr "Устройство %s не найдено"

#: ../tails_installer/creator.py:699
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr "Невозможно записать на %(device)s, пропускаю."

#: ../tails_installer/creator.py:719
#, python-format
msgid ""
"Some partitions of the target device %(device)s are mounted. They will be "
"unmounted before starting the installation process."
msgstr "Некоторые разделы целевого устройства %(device)s примонтированы. Они будут отмонтированы перед началом установки."

#: ../tails_installer/creator.py:762 ../tails_installer/creator.py:986
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr "Неизвестная файловая система. Ваше устройство нуждается в переформатировании."

#: ../tails_installer/creator.py:765 ../tails_installer/creator.py:989
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "Неподдерживаемая файловая система: %s"

#: ../tails_installer/creator.py:782
#, python-format
msgid "Unknown GLib exception while trying to mount device: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:786
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr "Невозможно смонтировать устройство %(message)s"

#: ../tails_installer/creator.py:791
msgid "No mount points found"
msgstr "Нет точек монтирования"

#: ../tails_installer/creator.py:802
#, python-format
msgid "Entering unmount_device for '%(device)s'"
msgstr "Открытие непримонтированного устройства для  '%(device)s'"

#: ../tails_installer/creator.py:812
#, python-format
msgid "Unmounting mounted filesystems on '%(device)s'"
msgstr "Размонтирование файловых систем на '%(device)s'"

#: ../tails_installer/creator.py:816
#, python-format
msgid "Unmounting '%(udi)s' on '%(device)s'"
msgstr "Размонтирование '%(udi)s' на '%(device)s'"

#: ../tails_installer/creator.py:826
#, python-format
msgid "Mount %s exists after unmounting"
msgstr "Точка монтирования %s существует во время монтирования"

#: ../tails_installer/creator.py:839
#, python-format
msgid "Partitioning device %(device)s"
msgstr "Разметка устройства %(device)s"

#: ../tails_installer/creator.py:917
#, python-format
msgid "Updating properties of system partition %(system_partition)s"
msgstr "Обновление свойств системного раздела %(system_partition)s"

#: ../tails_installer/creator.py:971
#, python-format
msgid "Unsupported device '%(device)s', please report a bug."
msgstr "Неподдерживаемое устройство '%(device)s', пожалуйста, сообщите об ошибке."

#: ../tails_installer/creator.py:974
msgid "Trying to continue anyway."
msgstr "Попытка продолжить все равно."

#: ../tails_installer/creator.py:983 ../tails_installer/creator.py:1376
msgid "Verifying filesystem..."
msgstr "Проверка файловой системы..."

#: ../tails_installer/creator.py:1007
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr "Невозможно изменить метку тома: %(message)s"

#: ../tails_installer/creator.py:1012 ../tails_installer/creator.py:1409
msgid "Installing bootloader..."
msgstr "Установка загрузчика..."

#: ../tails_installer/creator.py:1038
#, python-format
msgid "Could not find the '%s' COM32 module"
msgstr ""

#: ../tails_installer/creator.py:1046 ../tails_installer/creator.py:1427
#, python-format
msgid "Removing %(file)s"
msgstr "Removing %(file)s"

#: ../tails_installer/creator.py:1158
#, python-format
msgid "%s already bootable"
msgstr "%s уже является загрузочным"

#: ../tails_installer/creator.py:1178
msgid "Unable to find partition"
msgstr "Невозможно найти раздел"

#: ../tails_installer/creator.py:1201
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr "Форматирование %(device)s в FAT32"

#: ../tails_installer/creator.py:1261
msgid "Could not find syslinux' gptmbr.bin"
msgstr "Не удается найти syslinux' gptmbr.bin"

#: ../tails_installer/creator.py:1274
#, python-format
msgid "Reading extracted MBR from %s"
msgstr ""

#: ../tails_installer/creator.py:1278
#, python-format
msgid "Could not read the extracted MBR from %(path)s"
msgstr ""

#: ../tails_installer/creator.py:1291 ../tails_installer/creator.py:1292
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr "Сброс главной загрузочной записи %s"

#: ../tails_installer/creator.py:1297
msgid "Drive is a loopback, skipping MBR reset"
msgstr "Этот диск является петлевым устройством, пропускаем сброс MBR"

#: ../tails_installer/creator.py:1301 ../tails_installer/creator.py:1555
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr "Вычисление SHA1 от %s"

#: ../tails_installer/creator.py:1326
msgid "Synchronizing data on disk..."
msgstr "Сихронизирую данные на диске..."

#: ../tails_installer/creator.py:1368
msgid "Error probing device"
msgstr "Ошибка зондирования устройства"

#: ../tails_installer/creator.py:1370
msgid "Unable to find any supported device"
msgstr "Невозможно найти поддерживаемое устройство"

#: ../tails_installer/creator.py:1380
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr "Убедитесь, что USB-устройство подключено и отформатировано (FAT)"

#: ../tails_installer/creator.py:1383
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "Неподдерживаемая файловая система: %s\nПожалуйста, сделайте резервную копию данных и отформатируйте USB-устройство в файловую систему FAT."

#: ../tails_installer/creator.py:1450
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr "Невозможно получить Win32_LogicalDisk; win32com ничего не вернул"

#: ../tails_installer/creator.py:1503
msgid "Cannot find"
msgstr "Невозможно найти"

#: ../tails_installer/creator.py:1504
msgid ""
"Make sure to extract the entire tails-installer zip file before running this"
" program."
msgstr ""

#: ../tails_installer/gui.py:69
#, python-format
msgid "Unknown release: %s"
msgstr "Неизвестный выпуск: %s"

#: ../tails_installer/gui.py:73
#, python-format
msgid "Downloading %s..."
msgstr "Загрузка %s..."

#: ../tails_installer/gui.py:209
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "Ошибка: Не удалось установить метку или получить UUID вашего устройства.  Невозможно продолжить."

#: ../tails_installer/gui.py:258
#, python-format
msgid "Installation complete! (%s)"
msgstr "Установка завершена! (%s)"

#: ../tails_installer/gui.py:263
msgid "Tails installation failed!"
msgstr ""

#: ../tails_installer/gui.py:364
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr "Внимание: Для работы требуются права Администратора. Что бы получить их, нажмите правой клавишей на иконку приложения и откройте Свойства. В вкладке Совместимость, поставьте галочку на \"Выполнять эту программу от имени администратора\"."

#: ../tails_installer/gui.py:376 ../tails_installer/launcher.py:31
msgid "Tails Installer"
msgstr ""

#: ../tails_installer/gui.py:473
#, python-format
msgid "%(size)s %(vendor)s %(model)s device (%(device)s)"
msgstr ""

#: ../tails_installer/gui.py:484
msgid "No ISO image selected"
msgstr ""

#: ../tails_installer/gui.py:485
msgid "Please select a Tails ISO image."
msgstr ""

#: ../tails_installer/gui.py:524
msgid "No device suitable to install Tails could be found"
msgstr ""

#: ../tails_installer/gui.py:526
#, python-format
msgid "Please plug a USB flash drive or SD card of at least %0.1f GB."
msgstr ""

#: ../tails_installer/gui.py:560
#, python-format
msgid ""
"The USB stick \"%(pretty_name)s\" is configured as non-removable by its "
"manufacturer and Tails will fail to start on it. Please try installing on a "
"different model."
msgstr ""

#: ../tails_installer/gui.py:570
#, python-format
msgid ""
"The device \"%(pretty_name)s\" is too small to install Tails (at least "
"%(size)s GB is required)."
msgstr "Устройство \"%(pretty_name)s\" слишком мало для установки (нужно как минимум %(size)s GB)."

#: ../tails_installer/gui.py:592
msgid "An error happened while installing Tails"
msgstr ""

#: ../tails_installer/gui.py:604
msgid "Refreshing releases..."
msgstr "Обновление списка выпусков..."

#: ../tails_installer/gui.py:609
msgid "Releases updated!"
msgstr "Релизы обновлены!"

#: ../tails_installer/gui.py:651
msgid "Installation complete!"
msgstr "Установка завершена!"

#: ../tails_installer/gui.py:652
msgid "Installation was completed."
msgstr ""

#: ../tails_installer/gui.py:701
msgid "Unable to mount device"
msgstr "Невозможно смонтировать устройство"

#: ../tails_installer/gui.py:708 ../tails_installer/gui.py:736
msgid "Confirm the target USB stick"
msgstr ""

#: ../tails_installer/gui.py:709
#, python-format
msgid ""
"%(size)s %(vendor)s %(model)s device (%(device)s)\n"
"\n"
"All data on this USB stick will be lost."
msgstr ""

#: ../tails_installer/gui.py:728
#, python-format
msgid ""
"%(vendor)s %(model)s device (%(device)s)\n"
"\n"
"%(persistence_message)s"
msgstr ""

#: ../tails_installer/gui.py:782
msgid "Download complete!"
msgstr "Загрузка завершена!"

#: ../tails_installer/gui.py:786
msgid "Download failed: "
msgstr "Ошибка загрузки: "

#: ../tails_installer/gui.py:787
msgid "You can try again to resume your download"
msgstr "Вы можете попробовать продолжить загрузку"

#: ../tails_installer/gui.py:795
msgid ""
"The selected file is unreadable. Please fix its permissions or select "
"another file."
msgstr "Выбранный файл нечитабелен. Исправьте файл или выберите другой."

#: ../tails_installer/gui.py:801
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr "Невозможно использовать указанный файл. Попробуйте переместить ISO в корень диска (например C:\\)"

#: ../tails_installer/gui.py:807
#, python-format
msgid "%(filename)s selected"
msgstr "Выбрано %(filename)s"

#: ../tails_installer/source.py:28
msgid "Unable to find LiveOS on ISO"
msgstr ""

#: ../tails_installer/source.py:34
#, python-format
msgid "Could not guess underlying block device: %s"
msgstr ""

#: ../tails_installer/source.py:49
#, python-format
msgid ""
"There was a problem executing `%s`.\n"
"%s\n"
"%s"
msgstr ""

#: ../tails_installer/source.py:63
#, python-format
msgid "'%s' does not exist"
msgstr ""

#: ../tails_installer/source.py:65
#, python-format
msgid "'%s' is not a directory"
msgstr ""

#: ../tails_installer/source.py:75
#, python-format
msgid "Skipping '%(filename)s'"
msgstr ""

#: ../tails_installer/utils.py:44
#, python-format
msgid ""
"There was a problem executing `%s`.%s\n"
"%s"
msgstr ""

#: ../tails_installer/utils.py:124
msgid "Could not open device for writing."
msgstr ""

#: ../data/tails-installer.ui.h:1
msgid "Installation Instructions"
msgstr ""

#: ../data/tails-installer.ui.h:2
msgid "Clone the current Tails"
msgstr ""

#: ../data/tails-installer.ui.h:3
msgid "Use a downloaded Tails ISO image"
msgstr ""

#: ../data/tails-installer.ui.h:4
msgid "Select a distribution to download:"
msgstr ""

#: ../data/tails-installer.ui.h:5
msgid "Target USB stick:"
msgstr ""

#: ../data/tails-installer.ui.h:6
msgid "Reinstall (delete all data)"
msgstr ""

#: ../data/tails-installer.ui.h:7
msgid "Install Tails"
msgstr "Установить Tails"

#: ../data/tails-installer-launcher.ui.h:1
msgid ""
"To run Tails Installer you need an ISO image which can be downloaded from "
"the Tails website: <a "
"href=\"https://tails.boum.org/download/\">https://tails.boum.org/download/</a>"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:2
msgid "Install"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:3
msgid "• Install Tails on a new USB stick."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:4
msgid "• The USB stick that you install on is formatted and all data is lost."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:5
msgid "Upgrade"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:6
msgid "• Upgrade a Tails USB stick to the version of an ISO image."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:7
msgid ""
"• The encrypted persistent storage of the Tails USB stick that you upgrade "
"is preserved."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:8
msgid ""
"Need help? Read the <a "
"href=\"https://tails.boum.org/doc/first_steps/installation/\">documentation</a>"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:9
msgid "Install by cloning"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:10
msgid ""
"• Install Tails on another USB stick by copying the Tails system that you "
"are currently using."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:11
msgid ""
"• The encrypted persistent storage of the Tails USB stick that you are "
"currently using is not copied."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:12
msgid "Upgrade by cloning"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:13
msgid ""
"• Upgrade another Tails USB stick to the same version of Tails that you are "
"currently using."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:14
msgid "Upgrade from ISO"
msgstr ""

#: ../data/tails-installer-launcher.ui.h:15
msgid "• Upgrade another Tails USB stick to the version of an ISO image."
msgstr ""

#: ../data/tails-installer-launcher.ui.h:16
msgid ""
"Need help? Read the <a "
"href=\"file:///usr/share/doc/tails/website/doc/first_steps/installation.en.html\">documentation</a>"
msgstr ""
