# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Анатолий Гуськов <anatoliy.guskov@gmail.com>, 2009
# Andrey, 2016
# Andrey, 2017-2018
# Антон Толмачев <a.tolmachev@richart-consalt.ru>, 2015
# Boris Shminke, 2017
# Den Arefyev <>, 2012
# Denis Denis <stereodenis@gmail.com>, 2014
# Eugene, 2013
# Елисеев Дмитрий <inactive+ddark008@transifex.com>, 2012
# Иван Лапенков, 2015
# jujjer <jujjer@gmail.com>, 2013
# Misha Dyachuk <Wikia@scryptmail.com>, 2016-2017
# Oul Gocke <beandonlybe@yandex.ru>, 2013-2014
# Roberto Brigante, 2017
# Sergey Briskin, 2014
# sgtStrom, 2018
# tavarysh <tavarysh@riseup.net>, 2013
# Vladimir.Serykh <Vladimir.Serykh@extenza-studio.ru>, 2015
# vlasok <vlasok1987@yandex.ru>, 2012
# Yanis Voloshin <y@7i4.ru>, 2017
# Yulia <ypoyarko@redhat.com>, 2009
# Uho Lot <yavinav@gmail.com>, 2016
# pistenrammler <inactive+pistenrammler@transifex.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: The Tor Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-08-16 11:40+0200\n"
"PO-Revision-Date: 2018-08-16 14:46+0000\n"
"Last-Translator: carolyn <carolyn@anhalt.org>\n"
"Language-Team: Russian (http://www.transifex.com/otf/torproject/language/ru/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ru\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);\n"

#: ../tails_installer/creator.py:100
msgid "You must run this application as root"
msgstr "Вы должны запустить приложение с root правами"

#: ../tails_installer/creator.py:146
msgid "Extracting live image to the target device..."
msgstr "Извлечение образа на целевое устройство..."

#: ../tails_installer/creator.py:153
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr "Записано на скорости %(speed)d МБ/сек"

#: ../tails_installer/creator.py:296
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr "Ошибка выполнения команды: `%(command)s`.\nПодробный журнал ошибок сохранен в  '%(filename)s'."

#: ../tails_installer/creator.py:315
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr "Проверка SHA1 LiveCD образа..."

#: ../tails_installer/creator.py:319
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr "Проверка SHA256 LiveCD образа..."

#: ../tails_installer/creator.py:335
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr "Ошибка: Неверное SHA1 вашего Live CD образа.  Вы можете запустить программу с аргументом --noverify, чтобы пропустить проверку."

#: ../tails_installer/creator.py:341
msgid "Unknown ISO, skipping checksum verification"
msgstr "Неизвестный ISO, проверка контрольной суммы пропущена"

#: ../tails_installer/creator.py:353
#, python-format
msgid ""
"Not enough free space on device.\n"
"%dMB ISO + %dMB overlay > %dMB free space"
msgstr "Недостаточно места на устройстве.\n%dMB ISO + %dMB постоянное хранилище > %dMB свободного места"

#: ../tails_installer/creator.py:360
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "Создание %sМБ постоянного хранилища"

#: ../tails_installer/creator.py:421
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr "Невозможно копировать %(infile)s в %(outfile)s: %(message)s"

#: ../tails_installer/creator.py:435
msgid "Removing existing Live OS"
msgstr "Удаление существующей Live OS"

#: ../tails_installer/creator.py:444 ../tails_installer/creator.py:456
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr "Невозможно chmod %(file)s: %(message)s"

#: ../tails_installer/creator.py:449
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr "Невозможно удалить файл из предыдущей LiveOS: %(message)s"

#: ../tails_installer/creator.py:462
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr "Невозможно удалить директорию из предыдущей LiveOS: %(message)s"

#: ../tails_installer/creator.py:510
#, python-format
msgid "Cannot find device %s"
msgstr "Устройство %s не найдено"

#: ../tails_installer/creator.py:711
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr "Невозможно записать на %(device)s, пропускаю."

#: ../tails_installer/creator.py:741
#, python-format
msgid ""
"Some partitions of the target device %(device)s are mounted. They will be "
"unmounted before starting the installation process."
msgstr "Некоторые разделы целевого устройства %(device)s примонтированы. Они будут отмонтированы перед началом установки."

#: ../tails_installer/creator.py:784 ../tails_installer/creator.py:1008
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr "Неизвестная файловая система. Ваше устройство нуждается в переформатировании."

#: ../tails_installer/creator.py:787 ../tails_installer/creator.py:1011
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "Неподдерживаемая файловая система: %s"

#: ../tails_installer/creator.py:805
#, python-format
msgid "Unknown GLib exception while trying to mount device: %(message)s"
msgstr "Неизвестная ошибка GLib во время монтирования устройства: %(message)s"

#: ../tails_installer/creator.py:810
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr "Невозможно смонтировать устройство %(message)s"

#: ../tails_installer/creator.py:815
msgid "No mount points found"
msgstr "Нет точек монтирования"

#: ../tails_installer/creator.py:826
#, python-format
msgid "Entering unmount_device for '%(device)s'"
msgstr "Открытие непримонтированного устройства для  '%(device)s'"

#: ../tails_installer/creator.py:836
#, python-format
msgid "Unmounting mounted filesystems on '%(device)s'"
msgstr "Размонтирование файловых систем на '%(device)s'"

#: ../tails_installer/creator.py:840
#, python-format
msgid "Unmounting '%(udi)s' on '%(device)s'"
msgstr "Размонтирование '%(udi)s' на '%(device)s'"

#: ../tails_installer/creator.py:851
#, python-format
msgid "Mount %s exists after unmounting"
msgstr "Точка монтирования %s существует во время монтирования"

#: ../tails_installer/creator.py:864
#, python-format
msgid "Partitioning device %(device)s"
msgstr "Разметка устройства %(device)s"

#: ../tails_installer/creator.py:993
#, python-format
msgid "Unsupported device '%(device)s', please report a bug."
msgstr "Неподдерживаемое устройство '%(device)s', пожалуйста, сообщите об ошибке."

#: ../tails_installer/creator.py:996
msgid "Trying to continue anyway."
msgstr "Попытка продолжить все равно."

#: ../tails_installer/creator.py:1005 ../tails_installer/creator.py:1401
msgid "Verifying filesystem..."
msgstr "Проверка файловой системы..."

#: ../tails_installer/creator.py:1029
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr "Невозможно изменить метку тома: %(message)s"

#: ../tails_installer/creator.py:1034 ../tails_installer/creator.py:1434
msgid "Installing bootloader..."
msgstr "Установка загрузчика..."

#: ../tails_installer/creator.py:1061
#, python-format
msgid "Could not find the '%s' COM32 module"
msgstr "Не могу найти %s модуль COM32"

#: ../tails_installer/creator.py:1069 ../tails_installer/creator.py:1452
#, python-format
msgid "Removing %(file)s"
msgstr "Удаление %(file)s"

#: ../tails_installer/creator.py:1183
#, python-format
msgid "%s already bootable"
msgstr "%s уже является загрузочным"

#: ../tails_installer/creator.py:1203
msgid "Unable to find partition"
msgstr "Невозможно найти раздел"

#: ../tails_installer/creator.py:1226
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr "Форматирование %(device)s в FAT32"

#: ../tails_installer/creator.py:1286
msgid "Could not find syslinux' gptmbr.bin"
msgstr "Не удается найти syslinux' gptmbr.bin"

#: ../tails_installer/creator.py:1299
#, python-format
msgid "Reading extracted MBR from %s"
msgstr "Чтение извлеченной записи MBR из %s"

#: ../tails_installer/creator.py:1303
#, python-format
msgid "Could not read the extracted MBR from %(path)s"
msgstr "Не удается прочесть извлеченную запись MBR из %(path)s"

#: ../tails_installer/creator.py:1316 ../tails_installer/creator.py:1317
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr "Сброс главной загрузочной записи %s"

#: ../tails_installer/creator.py:1322
msgid "Drive is a loopback, skipping MBR reset"
msgstr "Устройство, пропускает сброс главной загрузочной записи MBR"

#: ../tails_installer/creator.py:1326 ../tails_installer/creator.py:1580
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr "Вычисление SHA1 от %s"

#: ../tails_installer/creator.py:1351
msgid "Synchronizing data on disk..."
msgstr "Сихронизирую данные на диске..."

#: ../tails_installer/creator.py:1393
msgid "Error probing device"
msgstr "Ошибка зондирования устройства"

#: ../tails_installer/creator.py:1395
msgid "Unable to find any supported device"
msgstr "Невозможно найти поддерживаемое устройство"

#: ../tails_installer/creator.py:1405
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr "Убедитесь, что USB-устройство подключено и отформатировано (FAT)"

#: ../tails_installer/creator.py:1408
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "Неподдерживаемая файловая система: %s\nПожалуйста, сделайте резервную копию данных и отформатируйте USB-устройство в файловую систему FAT."

#: ../tails_installer/creator.py:1475
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr "Невозможно получить Win32_LogicalDisk; win32com ничего не вернул"

#: ../tails_installer/creator.py:1528
msgid "Cannot find"
msgstr "Невозможно найти"

#: ../tails_installer/creator.py:1529
msgid ""
"Make sure to extract the entire tails-installer zip file before running this"
" program."
msgstr "Обязательно полностью распакуйте zip-файл с установщиком Tails перед запуском этой программы."

#: ../tails_installer/gui.py:69
#, python-format
msgid "Unknown release: %s"
msgstr "Неизвестный выпуск: %s"

#: ../tails_installer/gui.py:73
#, python-format
msgid "Downloading %s..."
msgstr "Загрузка %s..."

#: ../tails_installer/gui.py:213
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "Ошибка: Не удалось установить метку или получить UUID вашего устройства.  Невозможно продолжить."

#: ../tails_installer/gui.py:260
#, python-format
msgid "Installation complete! (%s)"
msgstr "Установка завершена! (%s)"

#: ../tails_installer/gui.py:265
msgid "Tails installation failed!"
msgstr "Ошибка установки Tails"

#: ../tails_installer/gui.py:361
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr "Внимание: Для работы требуются права Администратора. Что бы получить их, нажмите правой клавишей на иконку приложения и откройте Свойства. В вкладке Совместимость, поставьте галочку на \"Выполнять эту программу от имени администратора\"."

#: ../tails_installer/gui.py:373
msgid "Tails Installer"
msgstr "Установщик Tails"

#: ../tails_installer/gui.py:423 ../data/tails-installer.ui.h:2
msgid "Clone the current Tails"
msgstr "Клонировать текущий Tails."

#: ../tails_installer/gui.py:430 ../data/tails-installer.ui.h:3
msgid "Use a downloaded Tails ISO image"
msgstr "Используйте загруженный ISO образ Tails"

#: ../tails_installer/gui.py:467
msgid "Upgrade"
msgstr "Апгрейд"

#: ../tails_installer/gui.py:469
msgid "Manual Upgrade Instructions"
msgstr ""

#: ../tails_installer/gui.py:471
msgid "https://tails.boum.org/upgrade/"
msgstr ""

#: ../tails_installer/gui.py:479 ../data/tails-installer.ui.h:7
msgid "Install"
msgstr "Установить"

#: ../tails_installer/gui.py:482 ../data/tails-installer.ui.h:1
msgid "Installation Instructions"
msgstr "Инструкции по установке"

#: ../tails_installer/gui.py:484
msgid "https://tails.boum.org/install/"
msgstr ""

#: ../tails_installer/gui.py:490
#, python-format
msgid "%(size)s %(vendor)s %(model)s device (%(device)s)"
msgstr "%(size)s%(vendor)s%(model)s устройство (%(device)s)"

#: ../tails_installer/gui.py:502
msgid "No ISO image selected"
msgstr "Не выбрано ни одного ISO образа"

#: ../tails_installer/gui.py:503
msgid "Please select a Tails ISO image."
msgstr "Пожалуйста выберите ISO образ Tails"

#: ../tails_installer/gui.py:545
msgid "No device suitable to install Tails could be found"
msgstr "Не обнаружено устройств для установки Tails"

#: ../tails_installer/gui.py:547
#, python-format
msgid "Please plug a USB flash drive or SD card of at least %0.1f GB."
msgstr "Пожалуйста, подключите USB-флэшкарту или SD-карту размером не менее %0.1fГигабайт"

#: ../tails_installer/gui.py:581
#, python-format
msgid ""
"The USB stick \"%(pretty_name)s\" is configured as non-removable by its "
"manufacturer and Tails will fail to start on it. Please try installing on a "
"different model."
msgstr "USB накопитель \"%(pretty_name)s\" сконфигурирован изготовителем как несъемный, и Tails не сможет запуститься на нем. Пожалуйста, попробуйте установить на другую модель."

#: ../tails_installer/gui.py:591
#, python-format
msgid ""
"The device \"%(pretty_name)s\" is too small to install Tails (at least "
"%(size)s GB is required)."
msgstr "Устройство \"%(pretty_name)s\" слишком мало для установки (нужно как минимум %(size)s GB)."

#: ../tails_installer/gui.py:604
#, python-format
msgid ""
"To upgrade device \"%(pretty_name)s\" from this Tails, you need to use a downloaded Tails ISO image:\n"
"https://tails.boum.org/install/download"
msgstr ""

#: ../tails_installer/gui.py:625
msgid "An error happened while installing Tails"
msgstr "Ошибка при установке Tails"

#: ../tails_installer/gui.py:637
msgid "Refreshing releases..."
msgstr "Обновление списка выпусков..."

#: ../tails_installer/gui.py:642
msgid "Releases updated!"
msgstr "Релизы обновлены!"

#: ../tails_installer/gui.py:695
msgid "Installation complete!"
msgstr "Установка завершена!"

#: ../tails_installer/gui.py:744
msgid "Unable to mount device"
msgstr "Невозможно смонтировать устройство"

#: ../tails_installer/gui.py:751 ../tails_installer/gui.py:783
msgid "Confirm the target USB stick"
msgstr "Подтвердите выбранное USB устройство"

#: ../tails_installer/gui.py:752
#, python-format
msgid ""
"%(size)s %(vendor)s %(model)s device (%(device)s)\n"
"\n"
"All data on this USB stick will be lost."
msgstr "%(size)s%(vendor)s%(model)sустройства (%(device)s)\n\nВсе данные на этом USB накопителе будут потеряны."

#: ../tails_installer/gui.py:770
#, python-format
msgid "%(parent_size)s %(vendor)s %(model)s device (%(device)s)"
msgstr "%(parent_size)s%(vendor)s%(model)s устройство (%(device)s)"

#: ../tails_installer/gui.py:778
msgid ""
"\n"
"\n"
"The persistent storage on this USB stick will be preserved."
msgstr "\n\nПостоянное хранилище на этом USB устройстве будет сохранено."

#: ../tails_installer/gui.py:779
#, python-format
msgid "%(description)s%(persistence_message)s"
msgstr "%(description)s%(persistence_message)s"

#: ../tails_installer/gui.py:821
msgid "Download complete!"
msgstr "Загрузка завершена!"

#: ../tails_installer/gui.py:825
msgid "Download failed: "
msgstr "Ошибка загрузки: "

#: ../tails_installer/gui.py:826
msgid "You can try again to resume your download"
msgstr "Вы можете попробовать продолжить загрузку"

#: ../tails_installer/gui.py:834
msgid ""
"The selected file is unreadable. Please fix its permissions or select "
"another file."
msgstr "Выбранный файл нечитабелен. Исправьте файл или выберите другой."

#: ../tails_installer/gui.py:840
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr "Невозможно использовать указанный файл. Попробуйте переместить ISO в корень диска (например C:\\)"

#: ../tails_installer/gui.py:846
#, python-format
msgid "%(filename)s selected"
msgstr "Выбрано %(filename)s"

#: ../tails_installer/source.py:28
msgid "Unable to find LiveOS on ISO"
msgstr "Не удалось найти LiveOS в ISO-файле"

#: ../tails_installer/source.py:34
#, python-format
msgid "Could not guess underlying block device: %s"
msgstr "Не удалось определить используемый блочный файл устройства: %s"

#: ../tails_installer/source.py:49
#, python-format
msgid ""
"There was a problem executing `%s`.\n"
"%s\n"
"%s"
msgstr "Возникла проблема при исполнении `%s`.\n%s\n%s"

#: ../tails_installer/source.py:63
#, python-format
msgid "'%s' does not exist"
msgstr "'%s' не существует"

#: ../tails_installer/source.py:65
#, python-format
msgid "'%s' is not a directory"
msgstr "'%s' не является папкой"

#: ../tails_installer/source.py:75
#, python-format
msgid "Skipping '%(filename)s'"
msgstr "Пропущены '%(filename)s'"

#: ../tails_installer/utils.py:44
#, python-format
msgid ""
"There was a problem executing `%s`.%s\n"
"%s"
msgstr "Возникла проблема при исполнении `%s`.%s\n%s"

#: ../tails_installer/utils.py:124
msgid "Could not open device for writing."
msgstr "Не могу открыть устройство в режиме записи."

#: ../data/tails-installer.ui.h:4
msgid "Select a distribution to download:"
msgstr "Выберите раздачу для загрузки:"

#: ../data/tails-installer.ui.h:5
msgid "Target USB stick:"
msgstr "Выберите USB:"

#: ../data/tails-installer.ui.h:6
msgid "Reinstall (delete all data)"
msgstr "Переустановить (стереть все данные)"
