# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Sveinn í Felli <sv1@fellsnet.is>, 2010,2016-2018
# Sveinn í Felli <sv1@fellsnet.is>, 2010
msgid ""
msgstr ""
"Project-Id-Version: Tor Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-10-20 12:34+0200\n"
"PO-Revision-Date: 2018-11-04 16:20+0000\n"
"Last-Translator: Sveinn í Felli <sv1@fellsnet.is>\n"
"Language-Team: Icelandic (http://www.transifex.com/otf/torproject/language/is/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: is\n"
"Plural-Forms: nplurals=2; plural=(n % 10 != 1 || n % 100 == 11);\n"

#: ../tails_installer/creator.py:100
msgid "You must run this application as root"
msgstr "Þú verður að vera rót/root til að keyra þetta forrit"

#: ../tails_installer/creator.py:146
msgid "Extracting live image to the target device..."
msgstr "Afþjappa keyrslukerfi á viðtökutæki..."

#: ../tails_installer/creator.py:153
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr "Skrifaði á tækið með %(speed)d MB/sek"

#: ../tails_installer/creator.py:296
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr "Vandamál kom upp við að keyra eftirfarandi skipun: `%(command)s`.\nNákvæmari útlistun var skrifuð í '%(filename)s'."

#: ../tails_installer/creator.py:315
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr "Yfirfer SHA1-gátsummu Live ISO keyrslukerfis..."

#: ../tails_installer/creator.py:319
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr "Yfirfer SHA256-gátsummu Live ISO keyrslukerfis..."

#: ../tails_installer/creator.py:335
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr "Villa: SHA1-gátsumma Live ISO keyrslukerfisins er ógild. Þú getur keyrt þetta forrit með --noverify viðfanginu til að komast framhjá þessari öryggisprófun."

#: ../tails_installer/creator.py:341
msgid "Unknown ISO, skipping checksum verification"
msgstr "Óþekkt ISO-diskmynd, sleppi gátsummuprófun"

#: ../tails_installer/creator.py:353
#, python-format
msgid ""
"Not enough free space on device.\n"
"%dMB ISO + %dMB overlay > %dMB free space"
msgstr "Ekki nægilegt diskapláss á tækinu.\n%dMB ISO + %dMB yfirlögn > %dMB laust pláss"

#: ../tails_installer/creator.py:360
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "Bý til %sMB varanlega gagnageymslu"

#: ../tails_installer/creator.py:421
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr "Tekst ekki að afrita %(infile)s yfir í %(outfile)s: %(message)s"

#: ../tails_installer/creator.py:435
msgid "Removing existing Live OS"
msgstr "Fjarlægi Live ISO keyrslukerfi"

#: ../tails_installer/creator.py:444 ../tails_installer/creator.py:457
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr "Tekst ekki að keyra chmod %(file)s: %(message)s"

#: ../tails_installer/creator.py:450
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr "Gat ekki fjarlægt skrá úr fyrra Live ISO keyrslukerfi: %(message)s"

#: ../tails_installer/creator.py:464
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr "Gat ekki fjarlægt möppu úr fyrra Live ISO keyrslukerfi: %(message)s"

#: ../tails_installer/creator.py:512
#, python-format
msgid "Cannot find device %s"
msgstr "Get ekki fundið tækið %s"

#: ../tails_installer/creator.py:713
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr "Get ekki skrifað á %(device)s, sleppi þessu."

#: ../tails_installer/creator.py:743
#, python-format
msgid ""
"Some partitions of the target device %(device)s are mounted. They will be "
"unmounted before starting the installation process."
msgstr "Sumar disksneiðar marktækisins %(device)s eru tengdar í skráakerfið. Þær verða aftengdar áður en uppsetningarferlið hefst"

#: ../tails_installer/creator.py:786 ../tails_installer/creator.py:1010
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr "Óþekkt skráakerfi. Það gæti þurft að forsníða tækið."

#: ../tails_installer/creator.py:789 ../tails_installer/creator.py:1013
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "Óstutt skráakerfi: %s"

#: ../tails_installer/creator.py:807
#, python-format
msgid "Unknown GLib exception while trying to mount device: %(message)s"
msgstr "Óþekkt GLib-frávik þegar reynt var að tengja tæki í skráakerfi: %(message)s"

#: ../tails_installer/creator.py:812
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr "Tókst ekki að tengja tæki: %(message)s"

#: ../tails_installer/creator.py:817
msgid "No mount points found"
msgstr "Engir tengipunktar fundust"

#: ../tails_installer/creator.py:828
#, python-format
msgid "Entering unmount_device for '%(device)s'"
msgstr "Fer í unmount_device fyrir '%(device)s'"

#: ../tails_installer/creator.py:838
#, python-format
msgid "Unmounting mounted filesystems on '%(device)s'"
msgstr "Aftengi tengd skráakerfi á '%(device)s'"

#: ../tails_installer/creator.py:842
#, python-format
msgid "Unmounting '%(udi)s' on '%(device)s'"
msgstr "Aftengi '%(udi)s' á '%(device)s'"

#: ../tails_installer/creator.py:853
#, python-format
msgid "Mount %s exists after unmounting"
msgstr "Tengipunktur %s er til staðar eftir aftengingu"

#: ../tails_installer/creator.py:866
#, python-format
msgid "Partitioning device %(device)s"
msgstr "Sneiði geymslupláss tækisins %(device)s"

#: ../tails_installer/creator.py:995
#, python-format
msgid "Unsupported device '%(device)s', please report a bug."
msgstr "Óstutt tæki '%(device)s', tilkynntu um þessa villu."

#: ../tails_installer/creator.py:998
msgid "Trying to continue anyway."
msgstr "Reyni samt að halda áfram."

#: ../tails_installer/creator.py:1007 ../tails_installer/creator.py:1405
msgid "Verifying filesystem..."
msgstr "Yfirfer skráarkerfi..."

#: ../tails_installer/creator.py:1031
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr "Get ekki breytt heiti á gagnageymslu: %(message)s"

#: ../tails_installer/creator.py:1037 ../tails_installer/creator.py:1440
msgid "Installing bootloader..."
msgstr "Uppsetning ræsistjóra..."

#: ../tails_installer/creator.py:1064
#, python-format
msgid "Could not find the '%s' COM32 module"
msgstr "Gat ekki fundið '%s' COM32 eininguna"

#: ../tails_installer/creator.py:1072 ../tails_installer/creator.py:1458
#, python-format
msgid "Removing %(file)s"
msgstr "Fjarlægi %(file)s"

#: ../tails_installer/creator.py:1186
#, python-format
msgid "%s already bootable"
msgstr "%s er þegar ræsanlegt"

#: ../tails_installer/creator.py:1206
msgid "Unable to find partition"
msgstr "Gat ekki fundið disksneið"

#: ../tails_installer/creator.py:1229
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr "Forsníð %(device)s sem FAT32"

#: ../tails_installer/creator.py:1289
msgid "Could not find syslinux' gptmbr.bin"
msgstr "Gat ekki fundið syslinux' gptmbr.bin"

#: ../tails_installer/creator.py:1302
#, python-format
msgid "Reading extracted MBR from %s"
msgstr "Lesið afþjappaðan MBR-ræsigeira frá %s"

#: ../tails_installer/creator.py:1306
#, python-format
msgid "Could not read the extracted MBR from %(path)s"
msgstr "Gat ekki lesið afþjappaðan MBR-ræsigeira frá %(path)s"

#: ../tails_installer/creator.py:1319 ../tails_installer/creator.py:1320
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr "Frumstilli aðalræsifærslu (MBR) %s"

#: ../tails_installer/creator.py:1325
msgid "Drive is a loopback, skipping MBR reset"
msgstr "Drifið er hringtengt (loopback), sleppi endurstillingu á MBR-ræsigeira"

#: ../tails_installer/creator.py:1329 ../tails_installer/creator.py:1589
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr "Reikna SHA1 gátsummuna fyrir %s"

#: ../tails_installer/creator.py:1354
msgid "Synchronizing data on disk..."
msgstr "Samræmi gögn á diski..."

#: ../tails_installer/creator.py:1397
msgid "Error probing device"
msgstr "Villa við að yfirfara tæki"

#: ../tails_installer/creator.py:1399
msgid "Unable to find any supported device"
msgstr "Fann ekki nein studd tæki"

#: ../tails_installer/creator.py:1409
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr "Gakktu úr skugga um að USB-lykillinn þinn sé tengdur og að hann sé forsniðinn með FAT-skráakerfi"

#: ../tails_installer/creator.py:1412
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "Óstutt skráakerfi: %s\nTaktu öryggisafrit af USB-lyklinum og forsníddu hann með FAT-skráakerfi."

#: ../tails_installer/creator.py:1481
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr "Tókst ekki að sækja Win32_LogicalDisk; win32com fyrirspurn skilaði engum niðurstöðum"

#: ../tails_installer/creator.py:1536
msgid "Cannot find"
msgstr "Get ekki fundið"

#: ../tails_installer/creator.py:1537
msgid ""
"Make sure to extract the entire tails-installer zip file before running this"
" program."
msgstr "Vertu viss um að afþjappa allri tails-installer zip-skránni áður en þú keyrir þetta forrit."

#: ../tails_installer/gui.py:69
#, python-format
msgid "Unknown release: %s"
msgstr "Óþekkt útgáfa: %s"

#: ../tails_installer/gui.py:73
#, python-format
msgid "Downloading %s..."
msgstr "Næ í %s..."

#: ../tails_installer/gui.py:213
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "Villa: gat ekki sett merkingu eða fengið UUID-auðkenni tækisins. Get ekki haldið áfram."

#: ../tails_installer/gui.py:260
#, python-format
msgid "Installation complete! (%s)"
msgstr "Uppsetningu lokið! (%s)"

#: ../tails_installer/gui.py:265
msgid "Tails installation failed!"
msgstr "Uppsetning Tails mistókst!"

#: ../tails_installer/gui.py:361
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr "Aðvörun: Þetta tól verður að keyra sem kerfisstjóri (administrator). Til að gera það, hægri-smelltu á táknmyndina og opnaðu eiginleikana (Properties). Á samhæfniflipanum (Compatibility), hakaðu við að keyra þetta forrit sem kerfisstjóri (Run this program as an administrator)."

#: ../tails_installer/gui.py:373
msgid "Tails Installer"
msgstr "Tails-uppsetningarforrit"

#: ../tails_installer/gui.py:423 ../data/tails-installer.ui.h:2
msgid "Clone the current Tails"
msgstr "Klóna núverandi Tails"

#: ../tails_installer/gui.py:430 ../data/tails-installer.ui.h:3
msgid "Use a downloaded Tails ISO image"
msgstr "Nota Tails ISO-diskmynd sem sótt var á netinu"

#: ../tails_installer/gui.py:467 ../tails_installer/gui.py:788
msgid "Upgrade"
msgstr "Uppfæra"

#: ../tails_installer/gui.py:469
msgid "Manual Upgrade Instructions"
msgstr "Leiðbeiningar fyrir handvirka uppfærslu"

#: ../tails_installer/gui.py:471
msgid "https://tails.boum.org/upgrade/"
msgstr "https://tails.boum.org/upgrade/"

#: ../tails_installer/gui.py:479 ../tails_installer/gui.py:700
#: ../tails_installer/gui.py:765 ../data/tails-installer.ui.h:7
msgid "Install"
msgstr "Setja upp"

#: ../tails_installer/gui.py:482 ../data/tails-installer.ui.h:1
msgid "Installation Instructions"
msgstr "Leiðbeiningar fyrir uppsetningu"

#: ../tails_installer/gui.py:484
msgid "https://tails.boum.org/install/"
msgstr "https://tails.boum.org/install/"

#: ../tails_installer/gui.py:490
#, python-format
msgid "%(size)s %(vendor)s %(model)s device (%(device)s)"
msgstr "%(size)s %(vendor)s %(model)s tæki (%(device)s)"

#: ../tails_installer/gui.py:502
msgid "No ISO image selected"
msgstr "Engin ISO-diskmynd valin"

#: ../tails_installer/gui.py:503
msgid "Please select a Tails ISO image."
msgstr "Veldu Tails ISO-diskmynd."

#: ../tails_installer/gui.py:545
msgid "No device suitable to install Tails could be found"
msgstr "Ekkert hentugt tæki fannst til uppsetningar á Tails"

#: ../tails_installer/gui.py:547
#, python-format
msgid "Please plug a USB flash drive or SD card of at least %0.1f GB."
msgstr "Tengdu USB-minnislykil eða SD-minniskort með að minnsta kosti %0.1f GB gagnarýmd."

#: ../tails_installer/gui.py:581
#, python-format
msgid ""
"The USB stick \"%(pretty_name)s\" is configured as non-removable by its "
"manufacturer and Tails will fail to start on it. Please try installing on a "
"different model."
msgstr "USB-minnislykillinn \"%(pretty_name)s\" er ekki hannaður frá framleiðanda til að vera útskiptanlegur, Tails mun því ekki geta ræst upp af honum. Prófaðu að nota einhverja aðra tegund minnislykils."

#: ../tails_installer/gui.py:591
#, python-format
msgid ""
"The device \"%(pretty_name)s\" is too small to install Tails (at least "
"%(size)s GB is required)."
msgstr "Tækið \"%(pretty_name)s\" er of lítið til að hægt sé að setja Tails upp á því (að minnsta kosti %(size)s GB eru nauðsynleg)."

#: ../tails_installer/gui.py:604
#, python-format
msgid ""
"To upgrade device \"%(pretty_name)s\" from this Tails, you need to use a downloaded Tails ISO image:\n"
"https://tails.boum.org/install/download"
msgstr "Til að uppfæra tækið \"%(pretty_name)s\" úr þessu tilviki Tails, þá þarftu að nota Tails ISO diskmynd sem þú nærð í hér:\nhttps://tails.boum.org/install/download"

#: ../tails_installer/gui.py:625
msgid "An error happened while installing Tails"
msgstr "Villa kom upp við að setja upp Tails"

#: ../tails_installer/gui.py:637
msgid "Refreshing releases..."
msgstr "Endurles útgáfur..."

#: ../tails_installer/gui.py:642
msgid "Releases updated!"
msgstr "Uppfærði útgáfur!"

#: ../tails_installer/gui.py:695
msgid "Installation complete!"
msgstr "Uppsetningu lokið!"

#: ../tails_installer/gui.py:711
msgid "Cancel"
msgstr "Hætta við"

#: ../tails_installer/gui.py:747
msgid "Unable to mount device"
msgstr "Tókst ekki að tengja tæki"

#: ../tails_installer/gui.py:754 ../tails_installer/gui.py:787
msgid "Confirm the target USB stick"
msgstr "Staðfestu USB-minnislykilinn sem á að skrifa á"

#: ../tails_installer/gui.py:755
#, python-format
msgid ""
"%(size)s %(vendor)s %(model)s device (%(device)s)\n"
"\n"
"All data on this USB stick will be lost."
msgstr "%(size)s %(vendor)s %(model)s tæki (%(device)s)\n\nÖll gögn á á þessum USB-lykli munu tapast."

#: ../tails_installer/gui.py:774
#, python-format
msgid "%(parent_size)s %(vendor)s %(model)s device (%(device)s)"
msgstr "%(parent_size)s %(vendor)s %(model)s tæki (%(device)s)"

#: ../tails_installer/gui.py:782
msgid ""
"\n"
"\n"
"The persistent storage on this USB stick will be preserved."
msgstr "\n\nVaranlegu gagnageymslunni á þessum USB-lykli verður haldið til haga"

#: ../tails_installer/gui.py:783
#, python-format
msgid "%(description)s%(persistence_message)s"
msgstr "%(description)s%(persistence_message)s"

#: ../tails_installer/gui.py:826
msgid "Download complete!"
msgstr "Niðurhali lokið!"

#: ../tails_installer/gui.py:830
msgid "Download failed: "
msgstr "Niðurhal mistókst: "

#: ../tails_installer/gui.py:831
msgid "You can try again to resume your download"
msgstr "Þú getur reynt aftur til að klára niðurhalið"

#: ../tails_installer/gui.py:839
msgid ""
"The selected file is unreadable. Please fix its permissions or select "
"another file."
msgstr "Skráin sem þú valdir er ekki lesanleg. Lagaðu heimildir hennar eða veldu aðra skrá."

#: ../tails_installer/gui.py:845
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr "Gat ekki notað völdu skrána. Það gæti gengið betur ef þú færir ISO-skrána á rót drifsins (dæmi: C:\\)"

#: ../tails_installer/gui.py:851
#, python-format
msgid "%(filename)s selected"
msgstr "%(filename)s valið"

#: ../tails_installer/source.py:28
msgid "Unable to find LiveOS on ISO"
msgstr "Get ekki fundið LiveOS-keyrslukerfi á ISO-diskmynd"

#: ../tails_installer/source.py:34
#, python-format
msgid "Could not guess underlying block device: %s"
msgstr "Gat ekki giskað á undirliggjandi blokkartæki: %s"

#: ../tails_installer/source.py:49
#, python-format
msgid ""
"There was a problem executing `%s`.\n"
"%s\n"
"%s"
msgstr "Það kom upp vandamál við að keyra `%s`.\n%s\n%s"

#: ../tails_installer/source.py:63
#, python-format
msgid "'%s' does not exist"
msgstr "'%s' er ekki til"

#: ../tails_installer/source.py:65
#, python-format
msgid "'%s' is not a directory"
msgstr "'%s' er ekki mappa"

#: ../tails_installer/source.py:75
#, python-format
msgid "Skipping '%(filename)s'"
msgstr "Sleppi '%(filename)s'"

#: ../tails_installer/utils.py:44
#, python-format
msgid ""
"There was a problem executing `%s`.%s\n"
"%s"
msgstr "Það kom upp vandamál við að keyra `%s`.%s\n%s"

#: ../tails_installer/utils.py:124
msgid "Could not open device for writing."
msgstr "Gat ekki opnað tæki fyrir skrifun."

#: ../data/tails-installer.ui.h:4
msgid "Select a distribution to download:"
msgstr "Veldu dreifingu til að sækja:"

#: ../data/tails-installer.ui.h:5
msgid "Target USB stick:"
msgstr "USB-minnislykill til að skrifa á:"

#: ../data/tails-installer.ui.h:6
msgid "Reinstall (delete all data)"
msgstr "Setja upp aftur (eyða öllum gögnum)"
